# -*- coding: utf-8 -*-
# English word database for crossword puzzle
# Format: (word, clue)

WORDS = [
    # --- 3 letters ---
    ("ACE", "Top card in a deck"),
    ("ACT", "Perform on stage"),
    ("ADD", "Sum up numbers"),
    ("AGE", "How old you are"),
    ("AID", "Help someone in need"),
    ("AIM", "Point at a target"),
    ("AIR", "What we breathe"),
    ("ALE", "Type of beer"),
    ("ANT", "Small industrious insect"),
    ("APE", "Large primate"),
    ("ARC", "Curved line or shape"),
    ("ARK", "Noah's famous boat"),
    ("ARM", "Body limb with a hand"),
    ("ART", "Creative expression"),
    ("ATE", "Past tense of eat"),
    ("AWE", "Feeling of wonder"),
    ("AXE", "Tool for chopping wood"),
    ("BAD", "Not good at all"),
    ("BAG", "Container for carrying things"),
    ("BAN", "Officially forbid something"),
    ("BAR", "Place to drink or metal rod"),
    ("BAT", "Flying mammal or cricket tool"),
    ("BED", "Furniture for sleeping"),
    ("BET", "Wager money on outcome"),
    ("BIG", "Large in size"),
    ("BIT", "Small piece or amount"),
    ("BOW", "Curved weapon or greeting gesture"),
    ("BOX", "Rectangular container"),
    ("BOY", "Young male person"),
    ("BUD", "Flower before it opens"),
    ("BUG", "Small insect or software error"),
    ("BUS", "Public transport vehicle"),
    ("BUT", "However, on the other hand"),
    ("BUY", "Purchase with money"),
    ("CAB", "Taxi vehicle"),
    ("CAN", "Metal container or ability"),
    ("CAP", "Hat that covers the head"),
    ("CAR", "Four-wheeled vehicle"),
    ("CAT", "Domestic feline pet"),
    ("COP", "Police officer"),
    ("COW", "Female bovine animal"),
    ("CRY", "Shed tears or shout"),
    ("CUB", "Young bear or lion"),
    ("CUP", "Drinking vessel with handle"),
    ("CUT", "Divide with a sharp tool"),
    ("DAD", "Father, male parent"),
    ("DAM", "Barrier across a river"),
    ("DAY", "Twenty-four hour period"),
    ("DEN", "Animal's hidden shelter"),
    ("DEW", "Morning moisture on grass"),
    ("DIG", "Excavate the earth"),
    ("DIM", "Not bright, faintly lit"),
    ("DIP", "Briefly immerse in liquid"),
    ("DOC", "Informal word for doctor"),
    ("DOG", "Man's best friend"),
    ("DOT", "Small round mark"),
    ("DRY", "Without moisture"),
    ("DUB", "Give a nickname"),
    ("DUE", "Expected or owed"),
    ("DUG", "Past tense of dig"),
    ("DYE", "Color a fabric"),
    ("EAR", "Organ for hearing"),
    ("EAT", "Consume food"),
    ("EEL", "Snake-like fish"),
    ("EGG", "Oval shell from a bird"),
    ("ELF", "Small magical creature"),
    ("ELK", "Large deer of North America"),
    ("ELM", "Type of deciduous tree"),
    ("EMU", "Large flightless bird"),
    ("END", "Final part of something"),
    ("ERA", "Historical time period"),
    ("EVE", "Night before a holiday"),
    ("EWE", "Female sheep"),
    ("EYE", "Organ of sight"),
    ("FAN", "Device for cooling air"),
    ("FAR", "Great distance away"),
    ("FAT", "Adipose body tissue"),
    ("FAX", "Document transmission machine"),
    ("FED", "Past tense of feed"),
    ("FEW", "Not many in number"),
    ("FIG", "Sweet Mediterranean fruit"),
    ("FIN", "Fish's swimming appendage"),
    ("FIT", "In good physical shape"),
    ("FIX", "Repair something broken"),
    ("FLY", "Travel through the air"),
    ("FOG", "Thick low-lying mist"),
    ("FOR", "In favor of or intended to"),
    ("FOX", "Cunning reddish canine"),
    ("FRY", "Cook in hot oil"),
    ("FUN", "Enjoyment and amusement"),
    ("FUR", "Soft animal hair"),
    ("GAP", "Opening or space between"),
    ("GAS", "State of matter like air"),
    ("GEL", "Semi-solid styling substance"),
    ("GEM", "Precious stone"),
    ("GET", "Obtain or receive"),
    ("GIG", "Live music performance"),
    ("GIN", "Juniper-flavored spirit"),
    ("GNU", "African wildebeest"),
    ("GOD", "Supreme divine being"),
    ("GOT", "Past tense of get"),
    ("GUM", "Chewy candy or mouth tissue"),
    ("GUN", "Firearm weapon"),
    ("GUT", "Intestine or instinct"),
    ("GUY", "Informal word for man"),
    ("GYM", "Place for physical exercise"),
    ("HAD", "Past tense of have"),
    ("HAM", "Cured pork meat"),
    ("HAS", "Possesses something"),
    ("HAT", "Head covering"),
    ("HAY", "Dried grass for animals"),
    ("HEN", "Female chicken"),
    ("HER", "Belonging to a woman"),
    ("HEW", "Chop with an axe"),
    ("HID", "Past tense of hide"),
    ("HIM", "Referring to a male"),
    ("HIP", "Joint connecting leg to body"),
    ("HIT", "Strike forcefully"),
    ("HOG", "Large domestic pig"),
    ("HOP", "Jump on one foot"),
    ("HOT", "High temperature"),
    ("HOW", "In what manner"),
    ("HUB", "Center of activity"),
    ("HUE", "Shade of a color"),
    ("HUG", "Embrace affectionately"),
    ("HUM", "Sing with closed lips"),
    ("HUT", "Small simple shelter"),
    ("ICE", "Frozen water"),
    ("ILL", "Not in good health"),
    ("IMP", "Mischievous little devil"),
    ("INK", "Liquid for writing"),
    ("INN", "Small lodging house"),
    ("ION", "Electrically charged atom"),
    ("IRE", "Intense anger"),
    ("IVY", "Climbing evergreen plant"),
    ("JAB", "Quick sharp punch"),
    ("JAM", "Fruit preserve or blockage"),
    ("JAR", "Glass container with lid"),
    ("JAW", "Bone of the mouth"),
    ("JAY", "Colorful noisy bird"),
    ("JET", "Fast aircraft or water stream"),
    ("JOB", "Paid work or occupation"),
    ("JOG", "Run at a slow pace"),
    ("JOT", "Write down quickly"),
    ("JOY", "Great happiness"),
    ("JUG", "Container for pouring liquids"),
    ("JUT", "Extend outward sharply"),

    # --- 4 letters ---
    ("ABLE", "Having the capacity to"),
    ("ARCH", "Curved structural element"),
    ("ATOM", "Smallest unit of an element"),
    ("AXIS", "Line of rotation"),
    ("BAIT", "Lure for fishing"),
    ("BAKE", "Cook in an oven"),
    ("BALD", "Without hair on head"),
    ("BALL", "Round object for games"),
    ("BAND", "Musical group"),
    ("BANK", "Financial institution"),
    ("BARK", "Sound a dog makes"),
    ("BARN", "Farm building for storage"),
    ("BASE", "Foundation or bottom"),
    ("BATH", "Washing in water"),
    ("BEAD", "Small decorative sphere"),
    ("BEAM", "Ray of light or structural support"),
    ("BEAN", "Edible seed pod"),
    ("BEAR", "Large furry mammal"),
    ("BEAT", "Strike repeatedly or rhythm"),
    ("BELL", "Metal instrument that rings"),
    ("BELT", "Strip worn around the waist"),
    ("BEND", "Curve or turn"),
    ("BIKE", "Two-wheeled vehicle"),
    ("BILL", "Statement of charges"),
    ("BIND", "Tie together tightly"),
    ("BIRD", "Feathered flying animal"),
    ("BITE", "Cut with teeth"),
    ("BLOW", "Strong gust of wind"),
    ("BLUE", "Color of the sky"),
    ("BLUR", "Make unclear or indistinct"),
    ("BOAT", "Watercraft for travel"),
    ("BODY", "Physical form of a person"),
    ("BOLD", "Brave and daring"),
    ("BOLT", "Metal fastener or lightning"),
    ("BOMB", "Explosive device"),
    ("BOND", "Connection or attachment"),
    ("BONE", "Hard tissue of skeleton"),
    ("BOOK", "Written work with pages"),
    ("BOOT", "Footwear covering the ankle"),
    ("BORE", "Make a hole or be tedious"),
    ("BORN", "Brought into existence"),
    ("BOSS", "Person in charge"),
    ("BOWL", "Round deep dish"),
    ("BULK", "Large size or quantity"),
    ("BULL", "Male bovine animal"),
    ("BUMP", "Light collision or raised area"),
    ("BURN", "Damage by fire or heat"),
    ("BUSH", "Dense shrubby plant"),
    ("BUSY", "Having much to do"),
    ("BUZZ", "Humming sound of insects"),
    ("CAFE", "Small restaurant for coffee"),
    ("CAGE", "Enclosure for animals"),
    ("CAKE", "Sweet baked dessert"),
    ("CALF", "Young cow or leg muscle"),
    ("CALL", "Communicate by phone"),
    ("CALM", "Peaceful and tranquil"),
    ("CAME", "Past tense of come"),
    ("CAMP", "Outdoor sleeping site"),
    ("CAPE", "Sleeveless cloak or headland"),
    ("CARD", "Flat piece of stiff paper"),
    ("CARE", "Look after with concern"),
    ("CART", "Wheeled transport vehicle"),
    ("CASE", "Container or legal matter"),
    ("CASH", "Money in coins and notes"),
    ("CAST", "Throw or group of actors"),
    ("CAVE", "Natural underground chamber"),
    ("CELL", "Basic unit of life"),
    ("CHEF", "Professional cook"),
    ("CHIN", "Lower part of the face"),
    ("CHIP", "Small piece broken off"),
    ("CITY", "Large urban settlement"),
    ("CLAM", "Bivalve shellfish"),
    ("CLAP", "Strike hands together"),
    ("CLAY", "Moldable earth material"),
    ("CLIP", "Fasten or short video"),
    ("CLUE", "Hint to solve a mystery"),
    ("COAL", "Black combustible rock"),
    ("COAT", "Outer garment for warmth"),
    ("CODE", "System of symbols or rules"),
    ("COIL", "Wind in spirals"),
    ("COIN", "Metal money disc"),
    ("COLD", "Low temperature"),
    ("COLT", "Young male horse"),
    ("COMB", "Tool for grooming hair"),
    ("COME", "Move toward speaker"),
    ("COOK", "Prepare food by heating"),
    ("COOL", "Moderately cold"),
    ("COPE", "Deal with successfully"),
    ("COPY", "Duplicate of original"),
    ("CORD", "Thick string or rope"),
    ("CORE", "Central essential part"),
    ("CORK", "Bottle stopper material"),
    ("CORN", "Yellow cereal grain"),
    ("COST", "Price to be paid"),
    ("COZY", "Warm and comfortable"),
    ("CRAB", "Crustacean with claws"),
    ("CREW", "Team working together"),
    ("CROP", "Cultivated plant harvest"),
    ("CROW", "Large black bird"),
    ("CUBE", "Six-faced solid shape"),
    ("CURE", "Remedy for disease"),
    ("CURL", "Form into spirals"),
    ("CUTE", "Attractively pretty"),
    ("DALE", "Broad valley"),
    ("DAME", "Woman of rank"),
    ("DAMP", "Slightly wet"),
    ("DARE", "Challenge to do something"),
    ("DARK", "Without light"),
    ("DART", "Small pointed missile"),
    ("DASH", "Run quickly or punctuation mark"),
    ("DATA", "Facts and information"),
    ("DAWN", "First light of day"),
    ("DEAL", "Agreement or transaction"),
    ("DEAR", "Beloved or expensive"),
    ("DEBT", "Money owed to another"),
    ("DECK", "Ship's floor or card set"),
    ("DEED", "Action performed deliberately"),
    ("DEEP", "Extending far down"),
    ("DEER", "Graceful antlered animal"),
    ("DEMO", "Demonstration or sample"),
    ("DENY", "Refuse to acknowledge"),
    ("DESK", "Table for working"),
    ("DIAL", "Rotating numbered disc"),
    ("DICE", "Small cubes for games"),
    ("DIET", "Regular food intake"),
    ("DIME", "Ten-cent coin"),
    ("DINE", "Eat dinner"),
    ("DIRT", "Loose earth or soil"),
    ("DISC", "Flat circular object"),
    ("DISH", "Plate for serving food"),
    ("DOCK", "Harbor platform for ships"),
    ("DOES", "Performs an action"),
    ("DOME", "Rounded vault structure"),
    ("DONE", "Finished or completed"),
    ("DOOM", "Terrible fate or destiny"),
    ("DOOR", "Entrance to a room"),
    ("DOSE", "Measured quantity of medicine"),
    ("DOVE", "White bird of peace"),
    ("DOWN", "Toward a lower position"),
    ("DOZE", "Sleep lightly"),
    ("DRAG", "Pull along the ground"),
    ("DRAW", "Create pictures with pencil"),
    ("DRIP", "Fall in drops"),
    ("DROP", "Let fall downward"),
    ("DRUG", "Medicinal substance"),
    ("DRUM", "Percussion instrument"),
    ("DUAL", "Having two parts"),
    ("DUCK", "Waterfowl that quacks"),
    ("DUEL", "Combat between two people"),
    ("DULL", "Not interesting or sharp"),
    ("DUMB", "Unable to speak"),
    ("DUMP", "Place for waste disposal"),
    ("DUNE", "Hill of windblown sand"),
    ("DUSK", "Twilight before night"),
    ("DUST", "Fine dry particles"),
    ("DUTY", "Moral or legal obligation"),
    ("EACH", "Every one individually"),
    ("EARL", "British noble rank"),
    ("EARN", "Receive money for work"),
    ("EASE", "Freedom from difficulty"),
    ("EAST", "Direction of sunrise"),
    ("EASY", "Not difficult"),
    ("ECHO", "Repeated reflected sound"),
    ("EDGE", "Border or sharp side"),
    ("EDIT", "Revise written material"),
    ("EPIC", "Grand in scale or heroic"),
    ("EVEN", "Level or divisible by two"),
    ("EVIL", "Morally wicked"),
    ("EXAM", "Test of knowledge"),
    ("EXIT", "Way out of a place"),
    ("FACE", "Front of the head"),
    ("FACT", "Something proven true"),
    ("FADE", "Gradually disappear"),
    ("FAIL", "Not succeed in attempt"),
    ("FAIR", "Just and impartial"),
    ("FAKE", "Not genuine or real"),
    ("FALL", "Drop from a height"),
    ("FAME", "State of being well known"),
    ("FANG", "Long sharp tooth"),
    ("FARE", "Price of transport"),
    ("FARM", "Land for growing crops"),
    ("FAST", "Moving at high speed"),
    ("FATE", "Predetermined destiny"),
    ("FEAR", "Feeling of danger"),
    ("FEAT", "Remarkable achievement"),
    ("FEED", "Give food to"),
    ("FEEL", "Perceive by touch"),
    ("FELT", "Thick pressed fabric"),
    ("FERN", "Leafy shade-loving plant"),
    ("FILE", "Folder for documents"),
    ("FILL", "Make completely full"),
    ("FILM", "Movie or thin layer"),
    ("FIND", "Discover or locate"),
    ("FINE", "Of high quality or penalty"),
    ("FIRE", "Burning combustion"),
    ("FIRM", "Solid or a company"),
    ("FISH", "Aquatic gill-breathing animal"),
    ("FIST", "Clenched hand"),
    ("FLAG", "National symbol on cloth"),
    ("FLAP", "Move wings up and down"),
    ("FLAT", "Level and even surface"),
    ("FLAW", "Imperfection or defect"),
    ("FLEA", "Tiny jumping parasite"),
    ("FLED", "Ran away quickly"),
    ("FLEW", "Past tense of fly"),
    ("FLIP", "Turn over quickly"),
    ("FLOAT", "Rest on water surface"),
    ("FLOW", "Move steadily and continuously"),
    ("FOAM", "Mass of small bubbles"),
    ("FOLD", "Bend over on itself"),
    ("FOLK", "People in general"),
    ("FOOD", "Substance eaten for nutrition"),
    ("FOOL", "Silly or unwise person"),
    ("FOOT", "Lower extremity of the leg"),
    ("FORD", "Shallow river crossing"),
    ("FORK", "Eating utensil with prongs"),
    ("FORM", "Shape or document to fill"),
    ("FORT", "Fortified military building"),
    ("FOUL", "Offensive or rule violation"),
    ("FREE", "Not imprisoned or costing nothing"),
    ("FROG", "Jumping amphibian"),
    ("FROM", "Starting point of origin"),
    ("FUEL", "Material that produces energy"),
    ("FULL", "Containing maximum amount"),
    ("FUND", "Sum of money for purpose"),
    ("FUSE", "Safety device for electricity"),
    ("FURY", "Extreme violent anger"),
    ("FUZZ", "Light fluffy fibers"),
    ("GAIN", "Obtain or increase"),
    ("GALE", "Very strong wind"),
    ("GAME", "Activity played for fun"),
    ("GAPE", "Stare with open mouth"),
    ("GARB", "Clothing or attire"),
    ("GATE", "Door in a wall or fence"),
    ("GAVE", "Past tense of give"),
    ("GAZE", "Look steadily at something"),
    ("GEAR", "Equipment or mechanism"),
    ("GIFT", "Present given freely"),
    ("GIST", "Main point or essence"),
    ("GIVE", "Hand over to someone"),
    ("GLAD", "Feeling pleasure and joy"),
    ("GLEE", "Great delight"),
    ("GLOW", "Emit steady light"),
    ("GLUE", "Adhesive substance"),
    ("GOAT", "Bearded farm animal"),
    ("GOES", "Travels or moves along"),
    ("GOLD", "Precious yellow metal"),
    ("GOLF", "Sport played with clubs"),
    ("GONE", "No longer present"),
    ("GOOD", "Of high quality"),
    ("GRAB", "Seize suddenly"),
    ("GRAM", "Unit of weight"),
    ("GRAY", "Color between black and white"),
    ("GREW", "Past tense of grow"),
    ("GRID", "Network of crossing lines"),
    ("GRIM", "Stern or forbidding"),
    ("GRIN", "Broad smile"),
    ("GRIP", "Hold tightly"),
    ("GRIT", "Coarse sand particles"),
    ("GROW", "Increase in size"),
    ("GULF", "Large bay or divide"),
    ("GUST", "Sudden rush of wind"),

    # --- 5 letters ---
    ("ABODE", "Place of residence"),
    ("ABOVE", "Higher than something"),
    ("ABUSE", "Cruel treatment of someone"),
    ("ACUTE", "Sharp or severe"),
    ("ADAPT", "Adjust to new conditions"),
    ("ADMIT", "Confess or allow entry"),
    ("ADOPT", "Take as one's own"),
    ("AGILE", "Quick and nimble"),
    ("ALARM", "Warning signal device"),
    ("ALIEN", "Being from another world"),
    ("ALIGN", "Arrange in a line"),
    ("ALIKE", "Similar in appearance"),
    ("ALIVE", "Living and breathing"),
    ("ALLOY", "Mixture of metals"),
    ("ALLOW", "Give permission"),
    ("ALONE", "Without any company"),
    ("AMONG", "In the middle of"),
    ("AMPLE", "More than enough"),
    ("ANGEL", "Heavenly spiritual being"),
    ("ANGER", "Strong feeling of displeasure"),
    ("ANGLE", "Space between two lines"),
    ("ANKLE", "Joint connecting foot to leg"),
    ("APPLE", "Common round fruit"),
    ("ARENA", "Enclosed area for events"),
    ("AROMA", "Pleasant distinctive smell"),
    ("ATLAS", "Book of maps"),
    ("ATTIC", "Room under the roof"),
    ("BADGE", "Identifying emblem worn"),
    ("BASIC", "Fundamental and essential"),
    ("BASIN", "Bowl-shaped container"),
    ("BATCH", "Group produced together"),
    ("BEACH", "Sandy shore by the sea"),
    ("BLADE", "Sharp cutting edge"),
    ("BLAME", "Hold responsible for fault"),
    ("BLAND", "Lacking strong flavor"),
    ("BLANK", "Empty or unmarked"),
    ("BLAST", "Powerful explosion"),
    ("BLAZE", "Bright burning fire"),
    ("BLEED", "Lose blood from wound"),
    ("BLEND", "Mix together smoothly"),
    ("BLESS", "Ask for divine favor"),
    ("BLIND", "Unable to see"),
    ("BLISS", "Perfect happiness"),
    ("BLOCK", "Solid piece of material"),
    ("BLOOM", "Flower in full beauty"),
    ("BLOWN", "Carried by the wind"),
    ("BOARD", "Flat piece of wood"),
    ("BOAST", "Brag about achievements"),
    ("BONUS", "Extra reward or payment"),
    ("BRAIN", "Organ of thought"),
    ("BRAND", "Product trademark name"),
    ("BRAVE", "Courageous and fearless"),
    ("BREAD", "Baked flour staple food"),
    ("BREAK", "Separate into pieces"),
    ("BREED", "Type of animal variety"),
    ("BRICK", "Building block of clay"),
    ("BRIDE", "Woman getting married"),
    ("BRIEF", "Short in duration"),
    ("BROAD", "Wide in extent"),
    ("BROOK", "Small flowing stream"),
    ("BRUSH", "Tool with bristles"),
    ("BUILD", "Construct something"),
    ("BUNCH", "Group clustered together"),
    ("BURST", "Break open suddenly"),
    ("CABIN", "Small wooden house"),
    ("CABLE", "Thick wire or rope"),
    ("CAMEL", "Desert animal with humps"),
    ("CARRY", "Transport from one place"),
    ("CATCH", "Capture or grab hold of"),
    ("CAUSE", "Reason something happens"),
    ("CEDAR", "Aromatic evergreen tree"),
    ("CHAIN", "Connected metal links"),
    ("CHAIR", "Seat with a back"),
    ("CHALK", "White writing stick"),
    ("CHAOS", "Complete disorder"),
    ("CHARM", "Attractive quality"),
    ("CHASE", "Pursue in order to catch"),
    ("CHEAP", "Low in price"),
    ("CHECK", "Examine for accuracy"),
    ("CHEER", "Shout of encouragement"),
    ("CHESS", "Strategic board game"),
    ("CHEST", "Front of the torso or box"),
    ("CHIEF", "Leader of a group"),
    ("CHILD", "Young human being"),
    ("CHILL", "Make or become cold"),
    ("CHORD", "Group of musical notes"),
    ("CLAIM", "Assert as true"),
    ("CLASH", "Violent conflict"),
    ("CLASS", "Group of students"),
    ("CLEAN", "Free from dirt"),
    ("CLEAR", "Easy to see through"),
    ("CLIFF", "Steep rock face"),
    ("CLIMB", "Go upward using effort"),
    ("CLING", "Hold on tightly"),
    ("CLOCK", "Time-telling device"),
    ("CLONE", "Genetically identical copy"),
    ("CLOSE", "Shut or nearby"),
    ("CLOTH", "Woven fabric material"),
    ("CLOUD", "White mass in the sky"),
    ("COACH", "Trainer or large vehicle"),
    ("COAST", "Land along the sea"),
    ("COLOR", "Visual property like red"),
    ("CORAL", "Marine organism forming reefs"),
    ("COUCH", "Comfortable sofa for sitting"),
    ("COUNT", "Determine the total number"),
    ("COURT", "Place of legal proceedings"),
    ("COVER", "Place something over"),
    ("CRACK", "Narrow break or opening"),
    ("CRAFT", "Skilled creative activity"),
    ("CRANE", "Tall lifting machine or bird"),
    ("CRASH", "Violent collision"),
    ("CRAZY", "Mentally deranged or wild"),
    ("CREAM", "Rich dairy product"),
    ("CRISP", "Firm and crunchy"),
    ("CROSS", "Go from one side to other"),
    ("CROWD", "Large gathering of people"),
    ("CROWN", "Royal headpiece"),
    ("CRUDE", "In a raw natural state"),
    ("CRUEL", "Causing pain deliberately"),
    ("CRUSH", "Press with great force"),
    ("CUBIC", "Having three dimensions"),
    ("CURVE", "Smoothly bending line"),
    ("CYCLE", "Series that repeats"),
    ("DAILY", "Happening every day"),
    ("DANCE", "Move rhythmically to music"),
    ("DEBUT", "First public appearance"),
    ("DECOR", "Style of interior furnishing"),
    ("DELAY", "Make something late"),
    ("DELTA", "River mouth formation"),
    ("DEMON", "Evil supernatural being"),
    ("DENSE", "Closely packed together"),
    ("DEPTH", "Distance downward"),
    ("DEVIL", "Supreme evil being"),
    ("DIGIT", "Finger or number symbol"),
    ("DRAFT", "Preliminary version"),
    ("DRAIN", "Channel for carrying water"),
    ("DRAMA", "Theatrical art form"),
    ("DRAPE", "Hang cloth loosely"),
    ("DREAM", "Images during sleep"),
    ("DRESS", "Woman's garment"),
    ("DRIFT", "Move slowly with current"),
    ("DRILL", "Tool for making holes"),
    ("DRINK", "Swallow liquid"),
    ("DRIVE", "Operate a vehicle"),
    ("DRONE", "Unmanned flying device"),
    ("DWARF", "Very small mythical being"),
    ("DWELL", "Live in a place"),
    ("EAGER", "Keen and enthusiastic"),
    ("EAGLE", "Large bird of prey"),
    ("EARLY", "Before the expected time"),
    ("EARTH", "Our home planet"),
    ("ELDER", "Older and more experienced"),
    ("EMPTY", "Containing nothing"),
    ("ENEMY", "Person who opposes another"),
    ("ENJOY", "Take pleasure in"),
    ("ENTER", "Come or go into"),
    ("EQUAL", "Same in value or amount"),
    ("ERROR", "Mistake or inaccuracy"),
    ("EVENT", "Something that happens"),
    ("EVERY", "Each one without exception"),
    ("EXACT", "Precise and accurate"),
    ("EXTRA", "More than what is usual"),
    ("FABLE", "Story with a moral lesson"),
    ("FAITH", "Complete trust or belief"),
    ("FALSE", "Not true or genuine"),
    ("FEAST", "Large elaborate meal"),
    ("FENCE", "Barrier around a property"),
    ("FIBER", "Thread-like structure"),
    ("FIELD", "Open area of land"),
    ("FIFTY", "Number equal to five tens"),
    ("FIGHT", "Engage in combat"),
    ("FINAL", "Last in a series"),
    ("FLAME", "Burning gas from fire"),
    ("FLASH", "Sudden burst of light"),
    ("FLESH", "Soft body tissue"),
    ("FLINT", "Hard stone for sparks"),
    ("FLOAT", "Rest on water surface"),
    ("FLOCK", "Group of birds or sheep"),
    ("FLOOD", "Overflow of water"),
    ("FLOOR", "Bottom surface of room"),
    ("FLORA", "Plant life of a region"),
    ("FLOUR", "Ground grain for baking"),
    ("FLUID", "Substance that flows"),
    ("FLUTE", "Woodwind musical instrument"),
    ("FOCUS", "Center of attention"),
    ("FORCE", "Strength or power exerted"),
    ("FORGE", "Create by heating metal"),
    ("FOUND", "Discovered or established"),
    ("FRAME", "Border or structure"),
    ("FRESH", "Recently made or obtained"),
    ("FRONT", "Forward-facing side"),
    ("FROST", "Ice crystals on surfaces"),
    ("FRUIT", "Edible plant product"),
    ("GIANT", "Enormously large being"),
    ("GLOBE", "Spherical model of Earth"),
    ("GLOOM", "Partial darkness"),
    ("GLORY", "Great honor and praise"),
    ("GOOSE", "Large waterbird"),
    ("GRACE", "Elegance of movement"),
    ("GRADE", "Level or degree of quality"),
    ("GRAIN", "Cereal crop seed"),
    ("GRAND", "Impressive and magnificent"),
    ("GRANT", "Give officially"),
    ("GRAPE", "Small fruit for wine"),
    ("GRASP", "Grip firmly"),
    ("GRASS", "Green ground covering plant"),
    ("GRAVE", "Burial place"),
    ("GREED", "Excessive desire for more"),
    ("GREEN", "Color of growing plants"),
    ("GREET", "Welcome someone warmly"),
    ("GRIEF", "Deep sorrow and sadness"),
    ("GRIND", "Crush into small particles"),
    ("GROUP", "Number of people together"),
    ("GROVE", "Small group of trees"),
    ("GROWN", "Fully developed in size"),
    ("GUARD", "Person who protects"),
    ("GUESS", "Estimate without certainty"),
    ("GUIDE", "Person who leads others"),
    ("GUILT", "Feeling of having done wrong"),
    ("HAIKU", "Japanese short poem form"),
    ("HAVEN", "Safe place of shelter"),
    ("HEART", "Organ that pumps blood"),
    ("HEAVY", "Of great weight"),
    ("HEDGE", "Boundary of bushes"),
    ("HERON", "Long-legged wading bird"),
    ("HORSE", "Large animal for riding"),
    ("HOTEL", "Building for overnight stays"),
    ("HOUSE", "Building for living in"),
    ("HUMAN", "Person or relating to people"),
    ("HUMOR", "Quality of being amusing"),
    ("IDEAL", "Perfect standard"),
    ("IMAGE", "Visual representation"),
    ("INDEX", "Alphabetical list of topics"),
    ("INNER", "Located on the inside"),
    ("INPUT", "Data entered into system"),
    ("IVORY", "White material from tusks"),
    ("JEWEL", "Precious cut stone"),
    ("JOINT", "Place where parts connect"),
    ("JUDGE", "Person who decides in court"),
    ("JUICE", "Liquid from fruit"),
    ("KAYAK", "Small narrow paddle boat"),
    ("KNIFE", "Cutting tool with blade"),
    ("KNACK", "Skill at doing something"),
    ("LABEL", "Tag identifying something"),
    ("LABOR", "Physical work or effort"),
    ("LASER", "Concentrated light beam"),
    ("LAYER", "Single thickness of material"),
    ("LEASE", "Rental agreement contract"),
    ("LEAVE", "Go away from a place"),
    ("LEMON", "Sour yellow citrus fruit"),
    ("LEVEL", "Flat horizontal surface"),
    ("LIGHT", "Electromagnetic radiation we see"),
    ("LIMIT", "Point beyond which no more"),
    ("LIVER", "Organ that filters blood"),
    ("LOCAL", "Relating to nearby area"),
    ("LODGE", "Small country house"),
    ("LOGIC", "Systematic reasoning"),
    ("LOOSE", "Not firmly fixed"),
    ("LUNAR", "Relating to the moon"),
    ("MAGIC", "Supernatural power"),
    ("MAJOR", "Greater in importance"),
    ("MANOR", "Large country estate"),
    ("MAPLE", "Tree with lobed leaves"),
    ("MARCH", "Walk in military manner"),
    ("MATCH", "Contest or fire-starting stick"),
    ("MAYOR", "Head of a city government"),
    ("MEDAL", "Award for achievement"),
    ("MERCY", "Compassion toward offenders"),
    ("METAL", "Shiny conductive material"),
    ("MIGHT", "Great power or strength"),
    ("MINOR", "Lesser in importance"),
    ("MIXER", "Device for blending"),
    ("MODEL", "Representation or example"),
    ("MONEY", "Medium of exchange"),
    ("MONTH", "One twelfth of a year"),
    ("MORAL", "Lesson about right conduct"),
    ("MOTOR", "Machine producing movement"),
    ("MOUNT", "Climb up or a mountain"),
    ("MOUSE", "Small rodent animal"),
    ("MOUTH", "Opening for eating and speaking"),
    ("MUDDY", "Covered with wet earth"),
    ("MUSIC", "Art of arranged sounds"),
    ("NAIVE", "Showing lack of experience"),
    ("NERVE", "Fiber transmitting signals"),
    ("NOBLE", "Of high moral character"),
    ("NOISE", "Unwanted loud sound"),
    ("NORTH", "Direction of the pole star"),
    ("NOVEL", "Long fictional story book"),
    ("NURSE", "Healthcare professional"),
    ("NYLON", "Synthetic fabric material"),
    ("OASIS", "Fertile spot in desert"),
    ("OCEAN", "Vast body of salt water"),
    ("OLIVE", "Small oval Mediterranean fruit"),
    ("ONION", "Pungent layered vegetable"),
    ("OPERA", "Musical dramatic art form"),
    ("ORBIT", "Path around a celestial body"),
    ("ORDER", "Arrangement or command"),
    ("ORGAN", "Body part with function"),
    ("OTHER", "Different from the first"),
    ("OUTER", "On the external side"),
    ("OWNER", "Person who possesses"),
    ("OXIDE", "Compound with oxygen"),
    ("OZONE", "Protective atmospheric gas"),
    ("PANDA", "Black and white bear"),
    ("PANEL", "Flat section of a surface"),
    ("PANIC", "Sudden overwhelming fear"),
    ("PASTE", "Thick sticky mixture"),
    ("PATCH", "Piece used for mending"),
    ("PAUSE", "Temporary stop"),
    ("PEACE", "Freedom from conflict"),
    ("PEACH", "Soft fuzzy stone fruit"),
    ("PEARL", "Gem formed in an oyster"),
    ("PHASE", "Stage in a process"),
    ("PIANO", "Keyboard musical instrument"),
    ("PIECE", "Part of a whole"),
    ("PILOT", "Person who flies aircraft"),
    ("PINCH", "Squeeze between fingers"),
    ("PITCH", "Throw or musical tone"),
    ("PIXEL", "Smallest unit of display"),
    ("PIZZA", "Italian flatbread dish"),
    ("PLACE", "Particular position or area"),
    ("PLAIN", "Simple or flat land"),
    ("PLANE", "Aircraft or flat surface"),
    ("PLANT", "Living organism that grows"),
    ("PLATE", "Flat dish for food"),
    ("PLAZA", "Public open square"),
    ("PLEAD", "Make an emotional appeal"),
    ("PLUMB", "Measure vertical depth"),
    ("PLUME", "Large conspicuous feather"),
    ("POINT", "Sharp end or location"),
    ("POLAR", "Relating to the poles"),
    ("POUND", "Unit of weight or currency"),
    ("POWER", "Ability to do something"),
    ("PRESS", "Push firmly against"),
    ("PRICE", "Amount of money charged"),
    ("PRIDE", "Feeling of self-worth"),
    ("PRIME", "Of first importance"),
    ("PRINT", "Produce text on paper"),
    ("PRIOR", "Existing before in time"),
    ("PRISM", "Transparent optical element"),
    ("PRIZE", "Award for winning"),
    ("PROBE", "Investigate thoroughly"),
    ("PROOF", "Evidence establishing truth"),
    ("PSALM", "Sacred song or hymn"),
    ("PULSE", "Rhythmic heartbeat"),
    ("PUPIL", "Student or eye center"),
    ("PURSE", "Small bag for money"),
    ("QUEEN", "Female royal ruler"),
    ("QUERY", "Question or inquiry"),
    ("QUEST", "Long search for something"),
    ("QUEUE", "Line of waiting people"),
    ("QUICK", "Moving at high speed"),
    ("QUIET", "Making little noise"),
    ("QUOTA", "Limited allowed quantity"),
    ("QUOTE", "Repeat someone's words"),
    ("RADAR", "Detection using radio waves"),
    ("RADIO", "Wireless sound broadcasting"),
    ("RAISE", "Lift to a higher position"),
    ("RALLY", "Mass meeting or recovery"),
    ("RANCH", "Large farm for livestock"),
    ("RANGE", "Extent of variation"),
    ("RAPID", "Very fast moving"),
    ("RAVEN", "Large black intelligent bird"),
    ("REACH", "Stretch out to touch"),
    ("REALM", "Kingdom or domain"),
    ("REIGN", "Rule as a monarch"),
    ("RIVAL", "Competing opponent"),
    ("RIVER", "Large flowing body of water"),
    ("ROBIN", "Small bird with red breast"),
    ("ROBOT", "Automated mechanical device"),
    ("ROCKY", "Full of rocks"),
    ("ROUGE", "Red cosmetic for cheeks"),
    ("ROUND", "Shaped like a circle"),
    ("ROUTE", "Way or course taken"),
    ("ROYAL", "Relating to a king or queen"),
    ("RURAL", "Relating to the countryside"),
    ("SADLY", "In an unhappy manner"),
    ("SAINT", "Holy person recognized by church"),
    ("SALAD", "Mixed vegetable dish"),
    ("SCALE", "Relative size or fish covering"),
    ("SCARE", "Frighten someone suddenly"),
    ("SCENE", "Place where event occurs"),
    ("SCENT", "Pleasant distinctive smell"),
    ("SCOPE", "Range or extent"),
    ("SCORE", "Points earned in game"),
    ("SCOUT", "Person sent to explore"),
    ("SENSE", "Faculty of perception"),
    ("SERVE", "Provide service to"),
    ("SHADE", "Slight darkness from blocked light"),
    ("SHALL", "Used to express future"),
    ("SHAME", "Feeling of disgrace"),
    ("SHAPE", "External form of object"),
    ("SHARE", "Give portion to others"),
    ("SHARK", "Large predatory fish"),
    ("SHARP", "Having a fine cutting edge"),
    ("SHELF", "Flat board for storage"),
    ("SHELL", "Hard outer covering"),
    ("SHIFT", "Move or change position"),
    ("SHINE", "Emit bright light"),
    ("SHORE", "Land along water edge"),
    ("SHOUT", "Cry out loudly"),
    ("SIGHT", "Ability to see"),
    ("SILLY", "Lacking good sense"),
    ("SINCE", "From a time in the past"),
    ("SIREN", "Warning sound device"),
    ("SIXTY", "Number equal to six tens"),
    ("SKATE", "Glide on ice or wheels"),
    ("SKILL", "Ability from practice"),
    ("SKULL", "Bone framework of head"),
    ("SLAVE", "Person owned by another"),
    ("SLEEP", "Natural rest state"),
    ("SLICE", "Thin cut piece"),
    ("SLIDE", "Move smoothly along surface"),
    ("SLOPE", "Inclined surface or hill"),
    ("SMALL", "Little in size"),
    ("SMART", "Clever and intelligent"),
    ("SMELL", "Perceive with the nose"),
    ("SMILE", "Facial expression of happiness"),
    ("SMOKE", "Visible gas from burning"),
    ("SNACK", "Small amount of food"),
    ("SNAKE", "Limbless reptile"),
    ("SOLAR", "Relating to the sun"),
    ("SOLID", "Firm and stable state"),
    ("SOLVE", "Find answer to problem"),
    ("SONIC", "Relating to sound"),
    ("SOUTH", "Direction opposite north"),
    ("SPACE", "Unlimited expanse beyond Earth"),
    ("SPARE", "Extra kept in reserve"),
    ("SPARK", "Small fiery particle"),
    ("SPEAK", "Say words aloud"),
    ("SPEED", "Rate of movement"),
    ("SPELL", "Form words with letters"),
    ("SPEND", "Use money to buy things"),
    ("SPICE", "Aromatic food flavoring"),
    ("SPINE", "Backbone of the body"),
    ("SPLIT", "Break into parts"),
    ("SPOON", "Eating utensil with bowl"),
    ("SPRAY", "Scatter liquid in droplets"),
    ("SQUAD", "Small organized group"),
    ("STAGE", "Platform for performance"),
    ("STAIR", "Step in a staircase"),
    ("STAKE", "Strong pointed post"),
    ("STALE", "No longer fresh"),
    ("STALL", "Booth or delay progress"),
    ("STAMP", "Postal adhesive mark"),
    ("STAND", "Be in upright position"),
    ("STARE", "Look fixedly at something"),
    ("START", "Begin or commence"),
    ("STATE", "Condition or nation"),
    ("STEAM", "Water vapor from boiling"),
    ("STEEL", "Strong iron alloy"),
    ("STEEP", "Rising sharply"),
    ("STEER", "Guide direction of travel"),
    ("STERN", "Rear of a ship"),
    ("STICK", "Thin piece of wood"),
    ("STIFF", "Rigid and inflexible"),
    ("STILL", "Not moving or yet"),
    ("STING", "Sharp painful prick"),
    ("STOCK", "Supply of goods"),
    ("STONE", "Hard solid mineral"),
    ("STOOD", "Past tense of stand"),
    ("STOOL", "Seat without a back"),
    ("STORE", "Place for selling goods"),
    ("STORM", "Violent weather event"),
    ("STORY", "Account of events"),
    ("STOVE", "Cooking appliance"),
    ("STRAW", "Dried grain stalks"),
    ("STRIP", "Long narrow piece"),
    ("STUCK", "Unable to move"),
    ("STUDY", "Learn by reading"),
    ("STUFF", "Material or belongings"),
    ("STUMP", "Base of cut tree"),
    ("STYLE", "Distinctive manner"),
    ("SUGAR", "Sweet crystalline substance"),
    ("SUPER", "Of the highest quality"),
    ("SURGE", "Sudden powerful rush"),
    ("SWAMP", "Waterlogged area of land"),
    ("SWARM", "Large group of insects"),
    ("SWEAR", "Make solemn promise"),
    ("SWEEP", "Clean with a broom"),
    ("SWEET", "Having taste of sugar"),
    ("SWEPT", "Past tense of sweep"),
    ("SWIFT", "Moving very quickly"),
    ("SWING", "Move back and forth"),
    ("SWORD", "Weapon with long blade"),
    ("TABLE", "Flat-topped furniture piece"),
    ("TASTE", "Flavor perceived by tongue"),
    ("TEACH", "Instruct in knowledge"),
    ("THEFT", "Act of stealing"),
    ("THEME", "Central topic or subject"),
    ("THICK", "Large in diameter"),
    ("THING", "Object or item"),
    ("THINK", "Use the mind to reason"),
    ("THORN", "Sharp plant spike"),
    ("THREE", "Number after two"),
    ("THREW", "Past tense of throw"),
    ("THROW", "Propel through the air"),
    ("THUMB", "Shortest thickest finger"),
    ("TIDAL", "Relating to ocean tides"),
    ("TIGER", "Large striped wild cat"),
    ("TIMER", "Device that measures time"),
    ("TIRED", "In need of rest"),
    ("TITLE", "Name of a work"),
    ("TODAY", "On this present day"),
    ("TOKEN", "Symbol or small item"),
    ("TOOTH", "Hard structure in mouth"),
    ("TOPIC", "Subject of discussion"),
    ("TOTAL", "Complete amount or sum"),
    ("TOUCH", "Come in contact with"),
    ("TOUGH", "Strong and durable"),
    ("TOWER", "Tall narrow building"),
    ("TOXIC", "Poisonous substance"),
    ("TRACE", "Find or follow path of"),
    ("TRACK", "Path or course"),
    ("TRADE", "Buy and sell goods"),
    ("TRAIL", "Path through wilderness"),
    ("TRAIN", "Vehicles on railway"),
    ("TRAIT", "Distinguishing characteristic"),
    ("TRASH", "Waste material or rubbish"),
    ("TREAT", "Give something special"),
    ("TREND", "General direction of change"),
    ("TRIAL", "Legal court proceeding"),
    ("TRIBE", "Social group of families"),
    ("TRICK", "Cunning act to deceive"),
    ("TRIED", "Made an attempt"),
    ("TROOP", "Group of soldiers"),
    ("TRUCK", "Large road transport vehicle"),
    ("TRULY", "In a truthful manner"),
    ("TRUNK", "Main body of a tree"),
    ("TRUST", "Firm belief in reliability"),
    ("TRUTH", "State of being true"),
    ("TULIP", "Cup-shaped spring flower"),
    ("TUMOR", "Abnormal tissue growth"),
    ("TWIST", "Turn or rotate"),
    ("ULTRA", "Beyond the normal range"),
    ("UNDER", "Beneath or below"),
    ("UNION", "Joining together as one"),
    ("UNITE", "Come together as one"),
    ("UNITY", "State of being united"),
    ("UNTIL", "Up to the point that"),
    ("UPPER", "Higher in position"),
    ("URBAN", "Relating to a city"),
    ("USAGE", "Way something is used"),
    ("USUAL", "Normal or standard"),
    ("VALID", "Legally acceptable"),
    ("VALUE", "Worth or importance"),
    ("VAPOR", "Gas form of substance"),
    ("VAULT", "Secure storage room"),
    ("VERSE", "Line of poetry"),
    ("VIDEO", "Moving visual media"),
    ("VIGOR", "Physical strength and energy"),
    ("VIRAL", "Spreading rapidly"),
    ("VISIT", "Go to see someone"),
    ("VITAL", "Essential for life"),
    ("VIVID", "Intensely bright or clear"),
    ("VOCAL", "Relating to the voice"),
    ("VOICE", "Sound from the throat"),
    ("VOTER", "Person who casts ballot"),
    ("VOWEL", "Speech sound like A E I"),
    ("WAGON", "Four-wheeled transport"),
    ("WASTE", "Use carelessly or refuse"),
    ("WATCH", "Look at or timepiece"),
    ("WATER", "Clear liquid for drinking"),
    ("WHEAT", "Grain used for flour"),
    ("WHEEL", "Circular rotating device"),
    ("WHERE", "In or at what place"),
    ("WHICH", "What one of several"),
    ("WHILE", "During the time that"),
    ("WHITE", "Color of snow"),
    ("WHOLE", "Entire or complete"),
    ("WHOSE", "Belonging to whom"),
    ("WIDTH", "Measurement side to side"),
    ("WITCH", "Woman with magical powers"),
    ("WOMAN", "Adult female human"),
    ("WORLD", "The earth and its people"),
    ("WORST", "Most bad or severe"),
    ("WORTH", "Value or merit"),
    ("WOUND", "Injury to the body"),
    ("WRIST", "Joint connecting hand to arm"),
    ("WRITE", "Form letters on surface"),
    ("WRONG", "Not correct or just"),
    ("YACHT", "Sailing pleasure boat"),
    ("YIELD", "Produce or give way"),
    ("YOUNG", "In early stage of life"),
    ("YOUTH", "State of being young"),
    ("ZEBRA", "Black and white striped horse"),

    # --- 6+ letters ---
    ("ABSORB", "Take in or soak up"),
    ("ACCENT", "Way of pronouncing words"),
    ("ANCHOR", "Heavy device to moor ship"),
    ("ANNUAL", "Occurring once a year"),
    ("ARCTIC", "Extremely cold polar region"),
    ("AUTUMN", "Season between summer and winter"),
    ("BANANA", "Yellow curved tropical fruit"),
    ("BASKET", "Container woven from strips"),
    ("BATTLE", "Combat between armed forces"),
    ("BLANKET", "Warm bed covering"),
    ("BRIDGE", "Structure spanning a gap"),
    ("BRONZE", "Copper-tin alloy metal"),
    ("BUCKET", "Container with a handle"),
    ("BUDGET", "Financial spending plan"),
    ("BUTTER", "Spread made from cream"),
    ("BUTTON", "Fastener for clothing"),
    ("CACTUS", "Desert plant with spines"),
    ("CANDLE", "Wax stick that burns"),
    ("CANYON", "Deep narrow valley"),
    ("CARBON", "Element forming diamonds"),
    ("CARPET", "Floor covering fabric"),
    ("CASTLE", "Fortified medieval building"),
    ("CELLAR", "Underground storage room"),
    ("CHAPEL", "Small place of worship"),
    ("CHEESE", "Dairy food from milk"),
    ("CHERRY", "Small round red fruit"),
    ("CIRCLE", "Round closed plane figure"),
    ("CLINIC", "Medical treatment facility"),
    ("CLOSET", "Small room for storage"),
    ("COFFEE", "Caffeinated hot beverage"),
    ("COLONY", "Territory under foreign control"),
    ("COLUMN", "Vertical supporting pillar"),
    ("COMBAT", "Armed fighting or conflict"),
    ("COMEDY", "Amusing theatrical genre"),
    ("COMMON", "Occurring frequently"),
    ("COPPER", "Reddish conductive metal"),
    ("CORNER", "Point where lines meet"),
    ("COSMIC", "Relating to the universe"),
    ("COTTON", "Soft white fiber plant"),
    ("COURSE", "Direction or series of lessons"),
    ("CRISIS", "Time of intense difficulty"),
    ("CUSTOM", "Traditional practice"),
    ("DAMAGE", "Physical harm caused"),
    ("DANGER", "Possibility of harm"),
    ("DEBRIS", "Scattered remains of wreckage"),
    ("DEFEAT", "Win victory over"),
    ("DEFEND", "Protect from attack"),
    ("DEGREE", "Unit of measurement or rank"),
    ("DEMAND", "Insist on having"),
    ("DESERT", "Dry barren landscape"),
    ("DESIGN", "Plan or creative pattern"),
    ("DETECT", "Discover or identify"),
    ("DEVICE", "Tool made for purpose"),
    ("DIALOG", "Conversation between people"),
    ("DINNER", "Main evening meal"),
    ("DRAGON", "Mythical fire-breathing creature"),
    ("EMPIRE", "Group of nations under ruler"),
    ("ENERGY", "Power to do work"),
    ("ENGINE", "Machine producing power"),
    ("ESCAPE", "Break free from confinement"),
    ("FABRIC", "Cloth or woven material"),
    ("FALCON", "Fast bird of prey"),
    ("FAMILY", "Related group of people"),
    ("FAMINE", "Severe shortage of food"),
    ("FINGER", "Digit of the hand"),
    ("FLOWER", "Bloom of a plant"),
    ("FOLLOW", "Come after in sequence"),
    ("FOREST", "Large area of trees"),
    ("FOSSIL", "Preserved ancient remains"),
    ("FROZEN", "Turned into ice"),
    ("GALAXY", "System of billions of stars"),
    ("GARDEN", "Cultivated plant area"),
    ("GARLIC", "Pungent cooking bulb"),
    ("GEYSER", "Hot spring erupting water"),
    ("GINGER", "Spicy root used in cooking"),
    ("GLACIER", "Massive slow-moving ice body"),
    ("GOBLET", "Drinking cup with stem"),
    ("GOLDEN", "Made of or like gold"),
    ("GOSSIP", "Casual talk about others"),
    ("GRAVEL", "Small loose stones"),
    ("GUITAR", "Stringed musical instrument"),
    ("HAMMER", "Tool for driving nails"),
    ("HARBOR", "Sheltered water for ships"),
    ("HEAVEN", "Paradise or sky above"),
    ("HELMET", "Protective head covering"),
    ("HONEST", "Truthful and sincere"),
    ("HORROR", "Intense fear or dread"),
    ("HUNTER", "Person who hunts animals"),
    ("IGNITE", "Set on fire"),
    ("IMPACT", "Effect or collision"),
    ("IMPORT", "Bring goods from abroad"),
    ("INDOOR", "Inside a building"),
    ("INFANT", "Very young child"),
    ("INSECT", "Small six-legged creature"),
    ("ISLAND", "Land surrounded by water"),
    ("JACKET", "Short outer garment"),
    ("JAGUAR", "Spotted big cat"),
    ("JUNGLE", "Dense tropical forest"),
    ("KIDNEY", "Organ filtering blood"),
    ("KITTEN", "Young cat"),
    ("KNIGHT", "Medieval armored warrior"),
    ("LADDER", "Climbing device with rungs"),
    ("LAGOON", "Shallow body of water"),
    ("LEGEND", "Famous traditional story"),
    ("LESSON", "Period of instruction"),
    ("LETTER", "Written message or alphabet symbol"),
    ("LIZARD", "Small four-legged reptile"),
    ("MAGNET", "Object attracting iron"),
    ("MARBLE", "Hard metamorphic stone"),
    ("MARKET", "Place for buying goods"),
    ("MEADOW", "Field of grass and flowers"),
    ("MEMORY", "Ability to remember"),
    ("MENTAL", "Relating to the mind"),
    ("METEOR", "Shooting star in the sky"),
    ("MIRROR", "Reflective glass surface"),
    ("MONKEY", "Agile primate animal"),
    ("MUSEUM", "Building housing artifacts"),
    ("NAPKIN", "Cloth for wiping at meals"),
    ("NATION", "Country with government"),
    ("NATURE", "Natural world around us"),
    ("NEEDLE", "Thin pointed sewing tool"),
    ("NOTION", "Concept or idea"),
    ("NUMBER", "Mathematical counting value"),
    ("OBJECT", "Physical thing or to oppose"),
    ("OCTAVE", "Eight-note musical range"),
    ("ORANGE", "Citrus fruit or color"),
    ("OSPREY", "Fish-eating bird of prey"),
    ("OXYGEN", "Gas essential for breathing"),
    ("OYSTER", "Shellfish that makes pearls"),
    ("PADDLE", "Short oar for canoe"),
    ("PALACE", "Grand royal residence"),
    ("PARROT", "Colorful talking bird"),
    ("PASTRY", "Baked flour dough treats"),
    ("PATROL", "Keep watch over area"),
    ("PEBBLE", "Small smooth stone"),
    ("PENCIL", "Writing tool with graphite"),
    ("PEPPER", "Spicy seasoning or vegetable"),
    ("PERSON", "Individual human being"),
    ("PILLAR", "Tall vertical support"),
    ("PIRATE", "Sea robber on ships"),
    ("PLANET", "Celestial body orbiting star"),
    ("PLAQUE", "Commemorative flat tablet"),
    ("PLEDGE", "Solemn promise"),
    ("PLUNGE", "Dive or drop suddenly"),
    ("POCKET", "Small bag in clothing"),
    ("POISON", "Harmful toxic substance"),
    ("PORTAL", "Doorway or entrance"),
    ("POTATO", "Starchy root vegetable"),
    ("PRAYER", "Communication with deity"),
    ("PRINCE", "Son of a king"),
    ("PRISON", "Place of confinement"),
    ("PROFIT", "Financial gain"),
    ("PURPLE", "Color mixing red and blue"),
    ("PUZZLE", "Game requiring thought"),
    ("RABBIT", "Long-eared hopping animal"),
    ("RANDOM", "Without pattern or purpose"),
    ("RECIPE", "Cooking instructions"),
    ("RESCUE", "Save from danger"),
    ("RESULT", "Outcome or consequence"),
    ("RIBBON", "Narrow strip of fabric"),
    ("RIDDLE", "Puzzling question"),
    ("ROCKET", "Vehicle propelled upward"),
    ("RUBBER", "Elastic material"),
    ("SADDLE", "Seat on horse or bicycle"),
    ("SAILOR", "Person who works on ships"),
    ("SALMON", "Pink-fleshed fish"),
    ("SANDAL", "Open summer footwear"),
    ("SCARCE", "Insufficient in supply"),
    ("SEASON", "One of four yearly periods"),
    ("SECRET", "Something kept hidden"),
    ("SHIELD", "Protective barrier"),
    ("SIGNAL", "Indication or transmission"),
    ("SILVER", "Precious white metal"),
    ("SIMPLE", "Easy to understand"),
    ("SKETCH", "Quick rough drawing"),
    ("SLIGHT", "Small in amount"),
    ("SOCKET", "Hollow for fitting into"),
    ("SORROW", "Deep feeling of sadness"),
    ("SOURCE", "Origin or beginning point"),
    ("SPIDER", "Eight-legged arachnid"),
    ("SPIRIT", "Non-physical part of person"),
    ("SPONGE", "Absorbent cleaning material"),
    ("SPRING", "Season after winter"),
    ("STATUE", "Sculpted figure"),
    ("STEADY", "Firmly fixed and stable"),
    ("STOREY", "Level of a building"),
    ("STREAM", "Small flowing river"),
    ("STREET", "Road in a town"),
    ("STRICT", "Demanding exact compliance"),
    ("STRING", "Thin cord or thread"),
    ("STRONG", "Having great physical power"),
    ("STUDIO", "Artist's working room"),
    ("SUMMER", "Warmest season of year"),
    ("SUNSET", "Evening sky phenomenon"),
    ("SUPPLY", "Make available for use"),
    ("SYMBOL", "Sign representing something"),
    ("SYSTEM", "Organized set of parts"),
    ("TEMPLE", "Place of religious worship"),
    ("TENANT", "Person renting property"),
    ("THEORY", "System of ideas explaining"),
    ("THIRST", "Need for water"),
    ("THREAT", "Expression of harm"),
    ("THRONE", "Ceremonial seat of ruler"),
    ("TIMBER", "Wood for building"),
    ("TISSUE", "Soft paper or body material"),
    ("TONGUE", "Organ of taste in mouth"),
    ("TROPHY", "Prize for winning"),
    ("TUNNEL", "Underground passage"),
    ("TURTLE", "Reptile with shell"),
    ("UNIQUE", "One of a kind"),
    ("VALLEY", "Low land between hills"),
    ("VELVET", "Soft luxurious fabric"),
    ("VESSEL", "Ship or container"),
    ("VICTIM", "Person harmed by event"),
    ("VIOLET", "Purple-blue flower"),
    ("VISION", "Ability to see or dream"),
    ("VOYAGE", "Long journey by sea"),
    ("WALLET", "Small case for money"),
    ("WALNUT", "Wrinkled edible nut"),
    ("WEAPON", "Device for fighting"),
    ("WINTER", "Coldest season of year"),
    ("WISDOM", "Quality of being wise"),
    ("WONDER", "Feeling of amazement"),
    ("WOODEN", "Made of wood"),
    ("YELLOW", "Color of the sun"),
    ("ZENITH", "Highest point reached"),
    ("ZIGZAG", "Line with sharp turns"),
    ("ZOMBIE", "Undead creature in fiction"),
]

# Definitions organized by length (used by engine)
def get_words_by_length(min_len=3, max_len=15):
    """Returns words filtered by length."""
    return [(w, d) for w, d in WORDS if min_len <= len(w) <= max_len]

def get_clue(word):
    """Returns the clue for a word."""
    for w, d in WORDS:
        if w == word:
            return d
    return "Clue not available"
