# -*- coding: utf-8 -*-
# Database parole italiane per il cruciverba
# Formato: (parola, definizione)

WORDS = [
    # --- 3 lettere ---
    ("ACE", "Asso nei giochi di carte"),
    ("AGO", "Serve per cucire"),
    ("ALA", "Permette il volo"),
    ("AMO", "Sentimento profondo, prima persona"),
    ("APE", "Insetto che produce miele"),
    ("ARA", "Pappagallo colorato"),
    ("AVE", "Saluto latino"),
    ("BEL", "Aggettivo di bellezza"),
    ("BOA", "Serpente costrittore"),
    ("BUE", "Bovino da lavoro"),
    ("CAD", "Sistema di disegno al computer"),
    ("CUI", "Pronome relativo"),
    ("DNA", "Acido desossiribonucleico"),
    ("DUE", "Numero dopo l'uno"),
    ("ECO", "Ripetizione del suono"),
    ("ERA", "Periodo storico"),
    ("EST", "Punto cardinale dove sorge il sole"),
    ("ETA", "Gli anni di una persona"),
    ("FAR", "Verbo all'infinito troncato"),
    ("FIG", "Abbreviazione di figura"),
    ("GAS", "Stato della materia"),
    ("GEL", "Sostanza per capelli"),
    ("GRU", "Uccello trampoliere o macchina da cantiere"),
    ("IDE", "Ambiente di sviluppo integrato"),
    ("IRA", "Collera intensa"),
    ("ISO", "Organizzazione per gli standard"),
    ("IVA", "Imposta sul valore aggiunto"),
    ("LED", "Diodo a emissione luminosa"),
    ("MAI", "In nessun momento"),
    ("MAP", "Abbreviazione di mappa"),
    ("NEO", "Macchia sulla pelle"),
    ("NOI", "Pronome personale plurale"),
    ("OCA", "Uccello palmipede"),
    ("ORA", "Sessanta minuti"),
    ("ORO", "Metallo prezioso giallo"),
    ("PIO", "Devoto e religioso"),
    ("POI", "Dopo, in seguito"),
    ("RAM", "Memoria volatile del computer"),
    ("RAS", "Capo etiope"),
    ("REA", "Colpevole di un crimine"),
    ("REM", "Fase del sonno profondo"),
    ("RIO", "Piccolo corso d'acqua"),
    ("ROM", "Memoria di sola lettura"),
    ("RUE", "Via in francese"),
    ("SAI", "Verbo sapere, seconda persona"),
    ("SET", "Insieme in inglese"),
    ("SII", "Imperativo di essere"),
    ("SOL", "Nota musicale"),
    ("SPA", "Centro benessere"),
    ("TAO", "Filosofia cinese dell'armonia"),
    ("TRE", "Numero dopo il due"),
    ("UNO", "Primo numero naturale"),
    ("UVA", "Frutto della vite"),
    ("VIA", "Strada cittadina"),
    ("ZEN", "Filosofia orientale di meditazione"),
    ("ZII", "Fratelli dei genitori"),
    ("ZOO", "Giardino con animali"),

    # --- 4 lettere ---
    ("ACRE", "Misura di terreno anglosassone"),
    ("ALBA", "Momento in cui sorge il sole"),
    ("ALCE", "Grande cervide del nord"),
    ("ALMA", "Anima in spagnolo e latino"),
    ("ALTO", "Di grande statura"),
    ("AMEN", "Cosi sia in preghiera"),
    ("ANNO", "Dodici mesi"),
    ("ARCO", "Struttura curva in architettura"),
    ("AREA", "Superficie di una regione"),
    ("ARIA", "Gas che respiriamo"),
    ("ARMA", "Strumento di offesa o difesa"),
    ("ARTE", "Espressione creativa dell'uomo"),
    ("ASMA", "Malattia respiratoria"),
    ("AULA", "Stanza per lezioni"),
    ("AUTO", "Veicolo a motore"),
    ("BACO", "Larva del baco da seta"),
    ("BAIO", "Colore del cavallo marrone"),
    ("BASE", "Fondamento di qualcosa"),
    ("BENE", "Il contrario di male"),
    ("BETA", "Seconda lettera greca"),
    ("BICI", "Veicolo a due ruote a pedali"),
    ("BIGA", "Carro romano a due cavalli"),
    ("BITE", "Unita di misura informatica"),
    ("BOIA", "Esecutore di condanne capitali"),
    ("BORA", "Vento freddo del nordest"),
    ("BOSS", "Capo in inglese"),
    ("BUIO", "Assenza di luce"),
    ("CADO", "Verbo cadere, prima persona"),
    ("CANE", "Animale domestico fedele"),
    ("CAOS", "Disordine totale"),
    ("CAPO", "Chi comanda un gruppo"),
    ("CARA", "Aggettivo affettuoso femminile"),
    ("CASO", "Evento fortuito"),
    ("CENA", "Pasto serale"),
    ("CERO", "Grande candela da chiesa"),
    ("CHEF", "Cuoco professionista"),
    ("CIBO", "Alimento, nutrimento"),
    ("CIMA", "Vetta di una montagna"),
    ("CODA", "Appendice posteriore dell'animale"),
    ("COLA", "Bevanda gassata scura"),
    ("COME", "In quale modo"),
    ("CONO", "Figura geometrica a punta"),
    ("COPE", "Abbreviazione di coperta"),
    ("CORO", "Gruppo di cantori"),
    ("COSA", "Oggetto generico"),
    ("COTE", "Pietra per affilare"),
    ("COVO", "Rifugio segreto"),
    ("CUBO", "Solido con sei facce quadrate"),
    ("DADO", "Cubo per giochi o brodo"),
    ("DAMA", "Gioco da tavolo con pedine"),
    ("DARE", "Offrire qualcosa a qualcuno"),
    ("DATA", "Giorno mese e anno"),
    ("DIGA", "Sbarramento di un corso d'acqua"),
    ("DITO", "Parte terminale della mano"),
    ("DIVA", "Donna di grande talento"),
    ("DOCK", "Molo portuale"),
    ("DOGE", "Antico capo di Venezia"),
    ("DONO", "Regalo fatto con generosita"),
    ("DOPO", "Successivamente nel tempo"),
    ("DOSE", "Quantita di medicina"),
    ("DOTE", "Qualita naturale o beni nuziali"),
    ("DOVE", "In quale luogo"),
    ("DUCE", "Condottiero o capo militare"),
    ("DUNA", "Collina di sabbia"),
    ("DURO", "Resistente e compatto"),
    ("EBBE", "Passato remoto di avere"),
    ("ECHI", "Plurale di eco"),
    ("ELMO", "Protezione per la testa del guerriero"),
    ("EROE", "Persona di grande coraggio"),
    ("ESME", "Nome proprio di persona"),
    ("EURO", "Moneta dell'Unione Europea"),
    ("FAMA", "Notorieta e celebrita"),
    ("FARO", "Torre luminosa per naviganti"),
    ("FASE", "Stadio di un processo"),
    ("FATA", "Creatura magica delle fiabe"),
    ("FATO", "Destino ineluttabile"),
    ("FEDE", "Credenza profonda o anello nuziale"),
    ("FICO", "Frutto dolce mediterraneo"),
    ("FIDO", "Leale e fedele"),
    ("FILA", "Sequenza ordinata di persone"),
    ("FILM", "Opera cinematografica"),
    ("FINE", "Termine di qualcosa"),
    ("FOCA", "Mammifero marino"),
    ("FOGA", "Impeto e ardore"),
    ("FOLK", "Musica popolare tradizionale"),
    ("FORA", "Buca, perfora"),
    ("FORO", "Piazza dell'antica Roma"),
    ("FUGA", "Allontanamento rapido"),
    ("FUMO", "Prodotto della combustione"),
    ("FUNE", "Corda robusta"),
    ("GALA", "Festa elegante"),
    ("GARA", "Competizione sportiva"),
    ("GELO", "Freddo intenso"),
    ("GENE", "Unita dell'ereditarieta"),
    ("GIGA", "Prefisso per miliardo"),
    ("GITA", "Escursione di piacere"),
    ("GOLF", "Sport con mazza e pallina"),
    ("GOLA", "Parte anteriore del collo"),
    ("GONG", "Strumento musicale a percussione"),
    ("GORE", "Nome di un ex vicepresidente USA"),
    ("GOTA", "Guancia in dialetto"),
    ("GRES", "Ceramica per pavimenti"),
    ("GROG", "Bevanda calda con rum"),
    ("GUFO", "Rapace notturno"),
    ("GURU", "Maestro spirituale indiano"),
    ("IDEA", "Pensiero o concetto della mente"),
    ("IDRA", "Mostro mitologico a piu teste"),
    ("IMAM", "Guida religiosa islamica"),
    ("INCA", "Antico popolo del Peru"),
    ("INNO", "Canto solenne e patriottico"),
    ("IOTA", "Lettera greca molto piccola"),
    ("ISBA", "Tipica casa russa di legno"),
    ("ITER", "Percorso burocratico"),
    ("JUDO", "Arte marziale giapponese"),
    ("KIWI", "Frutto verde peloso"),
    ("LAMA", "Monaco tibetano o animale andino"),
    ("LANA", "Fibra tessile della pecora"),
    ("LARE", "Divinita domestica romana"),
    ("LATO", "Fianco di una figura geometrica"),
    ("LAVA", "Roccia fusa del vulcano"),
    ("LEGA", "Unione di stati o metalli"),
    ("LEGO", "Mattoncini giocattolo da costruzione"),
    ("LEVA", "Macchina semplice o chiamata militare"),
    ("LIDO", "Spiaggia attrezzata"),
    ("LIME", "Agrume verde piccolo"),
    ("LIMO", "Fango fine dei fiumi"),
    ("LIRA", "Antica moneta italiana"),
    ("LISA", "Liscia e levigata"),
    ("LITE", "Disputa o controversia legale"),
    ("LODE", "Elogio e approvazione"),
    ("LOGO", "Simbolo grafico di un'azienda"),
    ("LOTO", "Fiore sacro orientale"),
    ("LUCE", "Radiazione visibile all'occhio"),
    ("LUNA", "Satellite naturale della Terra"),
    ("LUPO", "Canide selvatico"),
    ("MAGO", "Chi pratica la magia"),
    ("MALE", "Il contrario di bene"),
    ("MANO", "Parte del corpo con cinque dita"),
    ("MARE", "Grande distesa di acqua salata"),
    ("MELA", "Frutto dell'albero di melo"),
    ("MENU", "Lista delle pietanze"),
    ("MESE", "Una delle dodici parti dell'anno"),
    ("META", "Obiettivo da raggiungere"),
    ("MICA", "Minerale sfaldabile in lamine"),
    ("MINA", "Ordigno esplosivo nascosto"),
    ("MINI", "Di dimensioni molto ridotte"),
    ("MIRA", "Puntamento di un'arma"),
    ("MITE", "Di carattere dolce e pacifico"),
    ("MODA", "Tendenza nell'abbigliamento"),
    ("MODO", "Maniera di fare qualcosa"),
    ("MOLE", "Grande massa o quantita"),
    ("MONO", "Prefisso che indica uno solo"),
    ("MORA", "Frutto di rovo o ritardo"),
    ("MORO", "Di carnagione scura"),
    ("MOTO", "Veicolo a due ruote a motore"),
    ("MULO", "Incrocio tra cavallo e asina"),
    ("MURO", "Parete di mattoni"),
    ("MUSA", "Ispiratrice delle arti"),
    ("NAVE", "Grande imbarcazione"),
    ("NASO", "Organo dell'olfatto"),
    ("NEON", "Gas nobile luminescente"),
    ("NERO", "Colore piu scuro"),
    ("NEVE", "Precipitazione bianca e fredda"),
    ("NIDO", "Casa degli uccelli"),
    ("NOME", "Parola che identifica"),
    ("NORD", "Punto cardinale della stella polare"),
    ("NOTA", "Segno musicale o appunto"),
    ("NUBE", "Ammasso di vapore nel cielo"),
    ("NUCA", "Parte posteriore del collo"),
    ("OBOE", "Strumento a fiato ad ancia doppia"),
    ("OLIO", "Liquido grasso per condire"),
    ("OLMO", "Albero dalle foglie dentate"),
    ("ONDE", "Increspature dell'acqua"),
    ("OPRA", "Forma poetica di opera"),
    ("ORCO", "Mostro delle fiabe"),
    ("ORMA", "Impronta del piede"),
    ("ORSO", "Grande mammifero plantigrado"),
    ("ORTO", "Terreno per coltivare verdure"),
    ("OSSO", "Parte dello scheletro"),
    ("OSTE", "Chi gestisce un'osteria"),
    ("PACE", "Assenza di guerra"),
    ("PALA", "Attrezzo per scavare"),
    ("PALO", "Sostegno verticale di legno"),
    ("PANE", "Alimento base di farina"),
    ("PARE", "Sembra, appare"),
    ("PARE", "Sembra o appare"),
    ("PARI", "Uguale in quantita"),
    ("PASO", "Passo in spagnolo"),
    ("PELO", "Filamento sulla pelle"),
    ("PENA", "Sofferenza o punizione"),
    ("PERO", "Albero che produce le pere"),
    ("PESO", "Forza di gravita su un corpo"),
    ("PILA", "Generatore di energia elettrica"),
    ("PINO", "Albero sempreverde con aghi"),
    ("PIPA", "Strumento per fumare tabacco"),
    ("POLO", "Estremita dell'asse terrestre"),
    ("POMO", "Frutto o elemento decorativo"),
    ("POPE", "Sacerdote ortodosso"),
    ("PORO", "Piccola apertura nella pelle"),
    ("POZO", "Pozzo in spagnolo"),
    ("PUMA", "Felino americano"),
    ("PUNK", "Genere musicale ribelle"),
    ("QUIZ", "Gioco a domande e risposte"),
    ("RADO", "Non fitto, sparso"),
    ("RAID", "Incursione improvvisa"),
    ("RAME", "Metallo rosso conduttore"),
    ("RANA", "Anfibio che salta"),
    ("RAPA", "Ortaggio a radice"),
    ("RASO", "Tessuto liscio e lucido"),
    ("RATA", "Pagamento periodico parziale"),
    ("RATTO", "Grosso topo"),
    ("RAVE", "Festa con musica elettronica"),
    ("RAZZA", "Specie o pesce cartilagineo"),
    ("REDE", "Forma arcaica di erede"),
    ("REMO", "Attrezzo per remare"),
    ("RENE", "Organo che filtra il sangue"),
    ("RESA", "Capitolazione o rendimento"),
    ("RETE", "Intreccio di fili o connessione"),
    ("RIMA", "Corrispondenza di suoni in poesia"),
    ("RISO", "Cereale asiatico o espressione allegra"),
    ("RITO", "Cerimonia religiosa o tradizionale"),
    ("RIVA", "Bordo di un fiume o lago"),
    ("ROBA", "Cose, oggetti generici"),
    ("ROCK", "Genere musicale energico"),
    ("ROGO", "Grande fuoco distruttore"),
    ("ROMA", "Capitale d'Italia"),
    ("ROSA", "Fiore profumato con spine"),
    ("ROTA", "Tribunale ecclesiastico"),
    ("ROVO", "Arbusto spinoso con more"),
    ("RUDE", "Rozzo e scortese"),
    ("RUGO", "Solco sulla pelle del viso"),
    ("RUPE", "Parete rocciosa scoscesa"),
    ("SAGO", "Fecola tropicale"),
    ("SALA", "Grande stanza per ricevimenti"),
    ("SALE", "Cloruro di sodio per condire"),
    ("SANO", "In buona salute"),
    ("SCIA", "Traccia lasciata nell'acqua"),
    ("SEBO", "Grasso animale"),
    ("SEDE", "Luogo di residenza ufficiale"),
    ("SEME", "Da cui nasce una pianta"),
    ("SERA", "Parte finale del giorno"),
    ("SETA", "Tessuto pregiato del baco"),
    ("SETE", "Bisogno di bere"),
    ("SILO", "Deposito per cereali"),
    ("SOLE", "Stella del nostro sistema"),
    ("SOLO", "Senza compagnia"),
    ("SOMA", "Carico trasportato a dorso"),
    ("SONO", "Verbo essere, prima persona plurale"),
    ("SUGO", "Condimento per la pasta"),
    ("SUMO", "Lotta giapponese"),
    ("TACO", "Piatto messicano con tortilla"),
    ("TALE", "Siffatto, di quel tipo"),
    ("TANA", "Rifugio di un animale"),
    ("TARA", "Peso dell'imballaggio"),
    ("TEMA", "Argomento di discussione"),
    ("TELA", "Tessuto per dipingere"),
    ("TIPO", "Genere o categoria"),
    ("TIRO", "Lancio verso un bersaglio"),
    ("TOGA", "Veste dell'antica Roma"),
    ("TONO", "Intensita della voce o colore"),
    ("TOPO", "Piccolo roditore"),
    ("TORO", "Bovino maschio"),
    ("TOFU", "Alimento di soia"),
    ("TUBO", "Condotto cilindrico cavo"),
    ("TUGA", "Sovrastruttura di una nave"),
    ("UREA", "Sostanza organica nei reni"),
    ("URNA", "Recipiente per le ceneri o il voto"),
    ("VAGO", "Indeterminato e impreciso"),
    ("VALE", "Ha un certo valore"),
    ("VANO", "Inutile o spazio vuoto"),
    ("VARO", "Messa in acqua di una nave"),
    ("VASO", "Recipiente per fiori o liquidi"),
    ("VELA", "Tela che cattura il vento"),
    ("VENA", "Vaso sanguigno di ritorno"),
    ("VERO", "Corrispondente alla realta"),
    ("VETO", "Divieto ufficiale"),
    ("VINO", "Bevanda alcolica dall'uva"),
    ("VISO", "Faccia di una persona"),
    ("VITA", "Esistenza di un essere vivente"),
    ("VITE", "Pianta dell'uva o elemento meccanico"),
    ("VOLO", "Spostamento nell'aria"),
    ("VOTO", "Espressione di preferenza elettorale"),
    ("YOGA", "Disciplina orientale del corpo"),
    ("ZAMA", "Lega di zinco"),
    ("ZANA", "Cesta per il trasporto"),
    ("ZELO", "Fervore e dedizione"),
    ("ZERO", "Numero che indica il nulla"),
    ("ZETA", "Ultima lettera dell'alfabeto"),
    ("ZINCO", "Elemento chimico metallico"),
    ("ZOLLA", "Pezzo di terra con erba"),
    ("ZONA", "Area delimitata di territorio"),

    # --- 5 lettere ---
    ("ABACO", "Antico strumento per calcolare"),
    ("ACETO", "Condimento acido per insalata"),
    ("ACQUA", "Liquido essenziale alla vita"),
    ("ADAGIO", "Tempo musicale lento"),
    ("AGLIO", "Bulbo aromatico per cucinare"),
    ("AIUTO", "Soccorso dato a chi ne ha bisogno"),
    ("ALANO", "Razza canina di grande taglia"),
    ("ALBUM", "Raccolta di fotografie o dischi"),
    ("ALIBI", "Prova di assenza dal luogo del crimine"),
    ("AMACA", "Letto sospeso di tela"),
    ("AMARO", "Sapore opposto al dolce"),
    ("AMINO", "Relativo agli aminoacidi"),
    ("AMORE", "Sentimento profondo di affetto"),
    ("ANIMA", "Essenza spirituale dell'essere"),
    ("ASILO", "Scuola per i bambini piccoli"),
    ("ATLETA", "Sportivo professionista"),
    ("ATOMO", "Particella fondamentale della materia"),
    ("AVENA", "Cereale per la colazione"),
    ("AVIDO", "Bramoso e desideroso"),
    ("BACIO", "Gesto affettuoso con le labbra"),
    ("BAGNO", "Stanza per lavarsi"),
    ("BALDO", "Coraggioso e ardito"),
    ("BANCO", "Mobile per sedersi a scuola"),
    ("BANCA", "Istituto di credito"),
    ("BANDA", "Gruppo musicale o di malviventi"),
    ("BARBA", "Peli sul viso maschile"),
    ("BARCA", "Piccola imbarcazione"),
    ("BASSO", "Di scarsa altezza"),
    ("BECCO", "Parte anteriore del capo degli uccelli"),
    ("BIRRA", "Bevanda alcolica di malto e luppolo"),
    ("BOLLA", "Sfera d'aria nell'acqua"),
    ("BORDO", "Margine estremo di una superficie"),
    ("BORSA", "Accessorio per portare oggetti"),
    ("BOSCO", "Area ricca di alberi"),
    ("BRAVO", "Abile e competente"),
    ("BRODO", "Liquido di cottura della carne"),
    ("BUONO", "Di qualita positiva"),
    ("BURRO", "Grasso alimentare dal latte"),
    ("BUSTA", "Involucro per lettere"),
    ("CACCIA", "Attivita di cattura di animali"),
    ("CALMA", "Stato di tranquillita"),
    ("CALZE", "Indumenti per i piedi"),
    ("CAMPO", "Terreno coltivato o sportivo"),
    ("CANTO", "Emissione melodica della voce"),
    ("CARTA", "Foglio per scrivere"),
    ("CASSA", "Contenitore di legno o sportello"),
    ("CAUSA", "Motivo di un evento"),
    ("CELLA", "Piccola stanza di prigione"),
    ("CERVO", "Mammifero con le corna ramificate"),
    ("CHINA", "Inchiostro nero o discesa"),
    ("CICLO", "Serie di eventi che si ripetono"),
    ("CIFRA", "Simbolo numerico"),
    ("CIGNO", "Elegante uccello acquatico bianco"),
    ("CIRCA", "Approssimativamente"),
    ("CLASSE", "Gruppo di alunni o categoria"),
    ("CLIMA", "Condizioni atmosferiche medie"),
    ("CLORO", "Elemento chimico disinfettante"),
    ("COBRA", "Serpente velenoso col cappuccio"),
    ("COLLE", "Piccola altura del terreno"),
    ("COLPO", "Urto improvviso e violento"),
    ("CONTE", "Titolo nobiliare"),
    ("COPPA", "Trofeo per il vincitore"),
    ("CORDA", "Filo intrecciato e resistente"),
    ("CORNO", "Appendice sul capo di animali"),
    ("CORPO", "Struttura fisica di un essere vivente"),
    ("CORSA", "Spostamento veloce a piedi"),
    ("CORTE", "Palazzo reale o tribunale"),
    ("COSTA", "Litorale marino"),
    ("CRANIO", "Struttura ossea della testa"),
    ("CREMA", "Dolce morbido o cosmetico"),
    ("CROCE", "Simbolo cristiano"),
    ("CUOCO", "Chi prepara i pasti"),
    ("CUORE", "Organo che pompa il sangue"),
    ("CURVA", "Linea non rettilinea"),
    ("DELTA", "Foce ramificata di un fiume"),
    ("DIETA", "Regime alimentare controllato"),
    ("DISCO", "Supporto musicale circolare"),
    ("DOLCE", "Sapore dello zucchero"),
    ("DONNA", "Essere umano femminile adulto"),
    ("DORSO", "Parte posteriore del corpo"),
    ("DRAGO", "Creatura mitologica alata"),
    ("DROGA", "Sostanza stupefacente"),
    ("DUOMO", "Cattedrale principale della citta"),
    ("ELICA", "Dispositivo rotante per la propulsione"),
    ("EMAIL", "Posta elettronica"),
    ("ENZIMA", "Proteina che catalizza reazioni"),
    ("EPOCA", "Periodo storico significativo"),
    ("ERBA", "Pianta verde dei prati"),
    ("ESAME", "Prova di valutazione scolastica"),
    ("EXTRA", "In piu, supplementare"),
    ("FANGO", "Miscela di terra e acqua"),
    ("FARSA", "Commedia ridicola e grossolana"),
    ("FAUNA", "Insieme degli animali di una regione"),
    ("FEUDO", "Territorio del signore medievale"),
    ("FIBRA", "Filamento naturale o artificiale"),
    ("FIENO", "Erba secca per il bestiame"),
    ("FIORE", "Organo riproduttivo della pianta"),
    ("FISSO", "Immobile, che non si muove"),
    ("FIUME", "Corso d'acqua che sfocia nel mare"),
    ("FLORA", "Insieme delle piante di una regione"),
    ("FONTE", "Sorgente d'acqua naturale"),
    ("FORMA", "Aspetto esteriore di un oggetto"),
    ("FORNO", "Apparecchio per cuocere"),
    ("FORTE", "Di grande potenza o solidita"),
    ("FOSSO", "Scavo lungo e stretto nel terreno"),
    ("FRANC", "Moneta di alcuni paesi"),
    ("FRASE", "Insieme di parole con senso compiuto"),
    ("FRECCIA", "Proiettile dell'arco"),
    ("FRENO", "Dispositivo per rallentare"),
    ("FRIGO", "Elettrodomestico per raffreddare"),
    ("FRODE", "Inganno a scopo di lucro"),
    ("FRONTE", "Parte superiore del viso"),
    ("FRUSTA", "Strumento flessibile per colpire"),
    ("FRUTTO", "Prodotto della pianta"),
    ("FUOCO", "Combustione con fiamma"),
    ("FURBO", "Astuto e scaltro"),
    ("GAMMA", "Serie graduata di elementi"),
    ("GATTO", "Felino domestico"),
    ("GENIO", "Persona di intelligenza eccezionale"),
    ("GESSO", "Minerite bianco per scrivere"),
    ("GHIRO", "Piccolo roditore che dorme molto"),
    ("GIOCO", "Attivita ludica e ricreativa"),
    ("GLOBO", "Sfera che rappresenta la Terra"),
    ("GOCCIA", "Piccola quantita di liquido"),
    ("GOMMA", "Materiale elastico"),
    ("GONNA", "Indumento femminile"),
    ("GRADO", "Unita di misura della temperatura"),
    ("GRANA", "Formaggio stagionato o difficolta"),
    ("GRANO", "Cereale per fare il pane"),
    ("GRIDO", "Voce forte e improvvisa"),
    ("GROTTA", "Cavita naturale nella roccia"),
    ("GRUPPO", "Insieme di persone o cose"),
    ("GUIDA", "Chi accompagna e dirige"),
    ("GUSTO", "Senso per percepire i sapori"),
    ("HOTEL", "Albergo per ospiti"),
    ("ICONA", "Immagine sacra o simbolo"),
    ("IGLOO", "Abitazione di ghiaccio degli Inuit"),
    ("INIZIO", "Principio di qualcosa"),
    ("INPUT", "Dati in ingresso al computer"),
    ("ISOLA", "Terra circondata dall'acqua"),
    ("LADRO", "Chi ruba agli altri"),
    ("LAMPO", "Scarica elettrica nel cielo"),
    ("LARGO", "Di grande ampiezza"),
    ("LASER", "Fascio di luce concentrata"),
    ("LATTE", "Liquido bianco nutriente"),
    ("LEGGE", "Norma giuridica dello stato"),
    ("LEGNO", "Materiale degli alberi"),
    ("LEMMA", "Voce di un dizionario"),
    ("LENTO", "Che si muove con poca velocita"),
    ("LEONE", "Re degli animali della savana"),
    ("LEPRE", "Mammifero simile al coniglio"),
    ("LIBRO", "Insieme di pagine rilegate"),
    ("LIEVE", "Leggero e delicato"),
    ("LINEA", "Segno continuo e sottile"),
    ("LITRO", "Unita di misura dei liquidi"),
    ("LOSCO", "Di aspetto sospetto e poco chiaro"),
    ("LOTTO", "Gioco a estrazione di numeri"),
    ("MAGRO", "Di poco peso corporeo"),
    ("MAMMA", "Genitrice affettuosa"),
    ("MANCO", "Nemmeno, neppure"),
    ("MAPPA", "Rappresentazione grafica di un luogo"),
    ("MARCA", "Nome commerciale di un prodotto"),
    ("MARZO", "Terzo mese dell'anno"),
    ("MASSA", "Grande quantita di materia"),
    ("MATTO", "Privo di ragione"),
    ("MEDIA", "Valore medio o mezzi di comunicazione"),
    ("MENTA", "Erba aromatica rinfrescante"),
    ("MERITO", "Riconoscimento per un'azione"),
    ("MERLO", "Uccello nero dal becco giallo"),
    ("MESSA", "Celebrazione liturgica cattolica"),
    ("MEZZO", "La parte centrale o un veicolo"),
    ("MICRO", "Prefisso che indica molto piccolo"),
    ("MIELE", "Dolce prodotto delle api"),
    ("MIRTO", "Arbusto aromatico mediterraneo"),
    ("MIXER", "Apparecchio per mescolare"),
    ("MOGLIE", "Coniuge femminile"),
    ("MOLLE", "Cedevole al tatto"),
    ("MOLTO", "In grande quantita"),
    ("MONDO", "Il pianeta Terra"),
    ("MONTE", "Grande rilievo del terreno"),
    ("MORTE", "Fine della vita"),
    ("MOSCA", "Insetto fastidioso volante"),
    ("MOSSE", "Spostamenti nel gioco degli scacchi"),
    ("MOTTO", "Frase breve e significativa"),
    ("MULTA", "Sanzione pecuniaria"),
    ("MUSEO", "Edificio per collezioni d'arte"),
    ("MUSICA", "Arte dei suoni"),
    ("NANNA", "Sonno dei bambini"),
    ("NASCE", "Viene al mondo"),
    ("NASPO", "Rocchetto per avvolgere fili"),
    ("NERVO", "Fascio di fibre del sistema nervoso"),
    ("NESSO", "Legame logico tra cose"),
    ("NINFA", "Divinita femminile della natura"),
    ("NOCCA", "Articolazione delle dita"),
    ("NORMA", "Regola da rispettare"),
    ("NOTTE", "Periodo di oscurita"),
    ("NOZZE", "Cerimonia matrimoniale"),
    ("NUOTO", "Sport acquatico"),
    ("NUOVO", "Appena fatto o mai usato"),
    ("OASI", "Zona fertile nel deserto"),
    ("OBOLO", "Piccola offerta di denaro"),
    ("OPERA", "Lavoro artistico o musicale"),
    ("ORGANO", "Parte del corpo con funzione specifica"),
    ("OVEST", "Punto cardinale del tramonto"),
    ("OZONO", "Gas protettivo dell'atmosfera"),
    ("PACCO", "Involto per spedizioni"),
    ("PADRE", "Genitore maschile"),
    ("PALCO", "Struttura rialzata del teatro"),
    ("PALLA", "Oggetto sferico per giocare"),
    ("PANCA", "Sedile lungo senza schienale"),
    ("PANDA", "Orso bianco e nero della Cina"),
    ("PANNO", "Pezzo di tessuto"),
    ("PAPPA", "Cibo morbido per neonati"),
    ("PARCO", "Area verde pubblica"),
    ("PASSO", "Movimento del piede camminando"),
    ("PASTA", "Alimento tipico italiano"),
    ("PASTO", "Atto del mangiare"),
    ("PATTO", "Accordo tra due parti"),
    ("PAURA", "Emozione di fronte al pericolo"),
    ("PENNA", "Strumento per scrivere"),
    ("PERLA", "Gemma prodotta dall'ostrica"),
    ("PESCA", "Frutto estivo o attivita sul fiume"),
    ("PESCE", "Animale acquatico con branchie"),
    ("PETTO", "Parte anteriore del torace"),
    ("PIAGA", "Ferita aperta e dolorosa"),
    ("PIANO", "Superficie orizzontale o strumento"),
    ("PIETRA", "Frammento di roccia"),
    ("PIGRO", "Che evita ogni fatica"),
    ("PINTA", "Misura di capacita per liquidi"),
    ("PISTA", "Tracciato per gare o indizi"),
    ("PIZZA", "Piatto italiano con pomodoro e mozzarella"),
    ("PLICO", "Involto di documenti"),
    ("POEMA", "Componimento poetico lungo"),
    ("POETA", "Chi scrive poesie"),
    ("PONTE", "Struttura che collega due sponde"),
    ("POPOLO", "Insieme dei cittadini"),
    ("PORTA", "Apertura per entrare e uscire"),
    ("PORTO", "Approdo per le navi"),
    ("POSTE", "Servizio per la corrispondenza"),
    ("POTERE", "Capacita di agire o governare"),
    ("POZZO", "Scavo per raggiungere l'acqua"),
    ("PRATO", "Distesa erbosa verde"),
    ("PREGO", "Risposta cortese a un ringraziamento"),
    ("PREMI", "Ricompense per i vincitori"),
    ("PREZZO", "Costo di un bene o servizio"),
    ("PRIMA", "Che precede tutte le altre"),
    ("PRODE", "Valoroso e coraggioso"),
    ("PROLE", "I figli di una coppia"),
    ("PROVA", "Test per verificare qualcosa"),
    ("PRUNO", "Arbusto spinoso selvatico"),
    ("PUNTO", "Segno grafico minimo"),
    ("QUADRO", "Dipinto incorniciato"),
    ("QUOTA", "Parte spettante o altitudine"),
    ("RADIO", "Apparecchio per ricevere onde sonore"),
    ("RANGO", "Posizione in una gerarchia"),
    ("REAME", "Territorio governato da un re"),
    ("REBUS", "Enigma illustrato con figure"),
    ("REGALO", "Dono fatto con piacere"),
    ("REGOLA", "Norma da seguire"),
    ("RETRO", "Parte posteriore"),
    ("RICCO", "Che possiede molte ricchezze"),
    ("RIGHE", "Linee tracciate su un foglio"),
    ("RITMO", "Cadenza regolare dei suoni"),
    ("ROCCA", "Fortezza su un'altura"),
    ("ROSPO", "Anfibio verrucoso"),
    ("ROSSO", "Colore del sangue"),
    ("RUOTA", "Disco che gira su un asse"),
    ("RUSSO", "Relativo alla Russia"),
    ("SACCO", "Grande recipiente di tela"),
    ("SAGRA", "Festa popolare paesana"),
    ("SALSA", "Condimento liquido per cibi"),
    ("SALTO", "Balzo da terra in aria"),
    ("SANTO", "Persona venerata dalla chiesa"),
    ("SAPONE", "Prodotto per lavare"),
    ("SASSO", "Pietra piccola e tonda"),
    ("SCENA", "Parte del palcoscenico o episodio"),
    ("SCUDO", "Protezione del guerriero"),
    ("SEGNO", "Traccia o simbolo"),
    ("SELLA", "Sedile per cavalcare"),
    ("SENSO", "Facolta percettiva del corpo"),
    ("SERIE", "Sequenza ordinata di elementi"),
    ("SIERO", "Parte liquida del sangue"),
    ("SIGMA", "Lettera dell'alfabeto greco"),
    ("SIRENA", "Creatura mitologica marina"),
    ("SOGNO", "Immagini durante il sonno"),
    ("SOMMA", "Risultato dell'addizione"),
    ("SORDO", "Che non puo udire"),
    ("SORTE", "Destino di una persona"),
    ("SOTTO", "In posizione inferiore"),
    ("SPADA", "Arma bianca con lama lunga"),
    ("SPAGO", "Filo resistente per legare"),
    ("SPAZIO", "Vuoto infinito dell'universo"),
    ("SPIA", "Chi raccoglie informazioni segrete"),
    ("SPINA", "Aculeo delle piante"),
    ("SPORT", "Attivita fisica competitiva"),
    ("STANZA", "Camera di un'abitazione"),
    ("STATO", "Nazione con un governo"),
    ("STELO", "Fusto della pianta"),
    ("STOP", "Segnale di arresto"),
    ("STORIA", "Narrazione degli eventi passati"),
    ("STUFA", "Apparecchio per riscaldare"),
    ("SUCCO", "Liquido estratto dalla frutta"),
    ("SUOLO", "Superficie della terra"),
    ("SUONO", "Vibrazione percepita dall'orecchio"),
    ("SVAGO", "Distrazione e divertimento"),
    ("TABELLA", "Prospetto ordinato di dati"),
    ("TACCO", "Rialzo sotto la scarpa"),
    ("TAPPA", "Fermata durante un viaggio"),
    ("TASSA", "Tributo pagato allo stato"),
    ("TAVOLO", "Mobile con piano orizzontale"),
    ("TEMPO", "Misura del divenire"),
    ("TERRA", "Il nostro pianeta o suolo"),
    ("TESTA", "Parte superiore del corpo"),
    ("TIGRE", "Grande felino a strisce"),
    ("TIZIO", "Persona qualunque"),
    ("TONNO", "Pesce di mare pregiato"),
    ("TORRE", "Costruzione alta e stretta"),
    ("TORTA", "Dolce da forno"),
    ("TOSCO", "Relativo alla Toscana"),
    ("TRENO", "Mezzo di trasporto su rotaie"),
    ("TRONO", "Seggio del re"),
    ("TROTA", "Pesce d'acqua dolce"),
    ("TUONO", "Rumore del fulmine"),
    ("TURNO", "Avvicendamento di persone"),
    ("UMORE", "Stato d'animo variabile"),
    ("UNICO", "Uno solo nel suo genere"),
    ("UNITA", "Singolo elemento di un insieme"),
    ("UOMO", "Essere umano maschile adulto"),
    ("UOVO", "Cellula riproduttiva degli uccelli"),
    ("USURA", "Prestito a interessi eccessivi"),
    ("UTILE", "Che reca vantaggio"),
    ("VALLE", "Depressione tra due montagne"),
    ("VAMPIRO", "Creatura leggendaria notturna"),
    ("VAPORE", "Gas prodotto dall'ebollizione"),
    ("VASCA", "Recipiente grande per l'acqua"),
    ("VASTO", "Di grande estensione"),
    ("VELENO", "Sostanza tossica mortale"),
    ("VENTO", "Movimento dell'aria"),
    ("VERDE", "Colore della natura"),
    ("VERME", "Invertebrato dal corpo allungato"),
    ("VERSO", "Riga di una poesia"),
    ("VETRO", "Materiale trasparente e fragile"),
    ("VIGNA", "Campo coltivato a vite"),
    ("VILLA", "Casa signorile con giardino"),
    ("VIOLA", "Colore tra rosso e blu"),
    ("VIRUS", "Agente infettivo microscopico"),
    ("VOCE", "Suono emesso dalla laringe"),
    ("VOLPE", "Mammifero furbo e astuto"),
    ("VOLTA", "Soffitto arcuato o occasione"),
    ("ZAINO", "Borsa portata sulle spalle"),
    ("ZAMPA", "Arto degli animali"),
    ("ZEBRA", "Equino a strisce bianche e nere"),
    ("ZOLFO", "Elemento chimico giallo"),
    ("ZUPPA", "Minestra densa e calda"),

    # --- 6+ lettere ---
    ("ABISSO", "Profondita senza fondo"),
    ("AGOSTO", "Ottavo mese dell'anno"),
    ("ALBERO", "Pianta con tronco e chioma"),
    ("AMIANTO", "Minerale fibroso pericoloso"),
    ("ANCORA", "Peso per fermare la nave"),
    ("ANGELO", "Essere celeste messaggero di Dio"),
    ("ANELLO", "Cerchio di metallo per il dito"),
    ("ANGOLO", "Intersezione di due linee"),
    ("ANTICO", "Molto vecchio nel tempo"),
    ("AGOSTO", "Mese estivo caldo"),
    ("ARGENTO", "Metallo prezioso bianco"),
    ("AZIONE", "Atto compiuto volontariamente"),
    ("BALCONE", "Sporgenza esterna di un edificio"),
    ("BALENA", "Mammifero marino gigantesco"),
    ("BANANA", "Frutto giallo tropicale"),
    ("BARISTA", "Chi serve al bar"),
    ("BERSAGLIO", "Obiettivo da colpire"),
    ("BOTTONE", "Chiusura per vestiti"),
    ("CALCIO", "Sport con il pallone rotondo"),
    ("CALICE", "Coppa per il vino sacro"),
    ("CAMERA", "Stanza da letto"),
    ("CAMINO", "Struttura per il fuoco domestico"),
    ("CANALE", "Via d'acqua artificiale"),
    ("CAROTA", "Ortaggio arancione"),
    ("CASTELLO", "Dimora fortificata medievale"),
    ("CELLULA", "Unita fondamentale dei viventi"),
    ("CENERE", "Residuo della combustione"),
    ("CERCHIO", "Figura geometrica rotonda"),
    ("CERVELLO", "Organo del pensiero"),
    ("CHIAVE", "Strumento per aprire serrature"),
    ("CILIEGIA", "Frutto rosso primaverile"),
    ("CINEMA", "Sala per proiezioni di film"),
    ("CIPOLLA", "Bulbo dal sapore forte"),
    ("COLONNA", "Sostegno verticale cilindrico"),
    ("COMETA", "Corpo celeste con la coda"),
    ("COMPITO", "Lavoro assegnato da svolgere"),
    ("CONIGLIO", "Animale dalle lunghe orecchie"),
    ("CORNICE", "Bordo decorativo di un quadro"),
    ("COTONE", "Fibra tessile bianca"),
    ("CUSCINO", "Morbido supporto per la testa"),
    ("DIAMANTE", "Pietra preziosa durissima"),
    ("DIPLOMA", "Attestato di studi compiuti"),
    ("DOMANDA", "Richiesta di informazione"),
    ("DRAMMA", "Genere teatrale serio"),
    ("ECLISSI", "Oscuramento di un astro"),
    ("ELEFANTE", "Il piu grande animale terrestre"),
    ("ENERGIA", "Capacita di compiere lavoro"),
    ("ENIGMA", "Indovinello misterioso"),
    ("ERUZIONE", "Emissione del vulcano"),
    ("ESEMPIO", "Modello da imitare"),
    ("ESTATE", "Stagione piu calda dell'anno"),
    ("ETERNA", "Che dura per sempre"),
    ("FATTORE", "Elemento che contribuisce"),
    ("FAVOLA", "Racconto fantastico per bambini"),
    ("FENICE", "Uccello mitologico che rinasce"),
    ("FINESTRA", "Apertura nel muro per la luce"),
    ("FONTANA", "Struttura con getti d'acqua"),
    ("FORMULA", "Espressione sintetica matematica"),
    ("FOSSILE", "Resto di organismo antico"),
    ("FRAGOLA", "Frutto rosso profumato"),
    ("FULMINE", "Scarica elettrica atmosferica"),
    ("GALASSIA", "Sistema di miliardi di stelle"),
    ("GABBIANO", "Uccello marino bianco"),
    ("GELATO", "Dolce freddo cremoso"),
    ("GEOMETRIA", "Scienza delle figure"),
    ("GHIACCIO", "Acqua solidificata dal freddo"),
    ("GIARDINO", "Spazio verde coltivato"),
    ("GINOCCHIO", "Articolazione della gamba"),
    ("GIRAFFA", "Animale col collo lunghissimo"),
    ("GOMITO", "Articolazione del braccio"),
    ("GRANCHIO", "Crostaceo con le chele"),
    ("GRISSINO", "Bastoncino di pane croccante"),
    ("GUANTO", "Indumento per la mano"),
    ("INCUDINE", "Attrezzo del fabbro"),
    ("INVERNO", "Stagione piu fredda"),
    ("IPOTESI", "Supposizione da verificare"),
    ("LAMPADA", "Fonte artificiale di luce"),
    ("LAVAGNA", "Superficie per scrivere in classe"),
    ("LIMONE", "Agrume giallo e aspro"),
    ("LOTTERIA", "Estrazione a premi"),
    ("LUCERTOLA", "Piccolo rettile veloce"),
    ("MAESTRO", "Insegnante di scuola"),
    ("MATITA", "Strumento per disegnare"),
    ("MELODIA", "Successione armoniosa di note"),
    ("MEMORIA", "Capacita di ricordare"),
    ("MERCATO", "Luogo di compravendita"),
    ("MIRACOLO", "Evento soprannaturale"),
    ("MOLECOLA", "Gruppo di atomi legati"),
    ("MONTAGNA", "Grande rilievo naturale"),
    ("MOSAICO", "Decorazione con tessere colorate"),
    ("MOTORE", "Macchina che produce movimento"),
    ("MURATORE", "Chi costruisce con i mattoni"),
    ("NAZIONE", "Popolo con territorio e governo"),
    ("NETTARE", "Bevanda degli dei o succo floreale"),
    ("NOTIZIA", "Informazione su un fatto recente"),
    ("NUVOLA", "Massa di vapore nel cielo"),
    ("OCEANO", "Grande distesa di acqua salata"),
    ("OLIVA", "Frutto dell'ulivo"),
    ("OMBRELLO", "Riparo portatile dalla pioggia"),
    ("ORBITA", "Traiettoria di un corpo celeste"),
    ("OROLOGIO", "Strumento che misura il tempo"),
    ("PAGINA", "Facciata di un foglio"),
    ("PALAZZO", "Grande edificio signorile"),
    ("PALUDE", "Terreno acquitrinoso"),
    ("PANTERA", "Felino nero della giungla"),
    ("PAPAVERO", "Fiore rosso dei campi"),
    ("PARADISO", "Luogo di beatitudine eterna"),
    ("PASSATO", "Il tempo trascorso"),
    ("PAVIMENTO", "Superficie su cui si cammina"),
    ("PECORA", "Animale che produce lana"),
    ("PENSIERO", "Attivita della mente"),
    ("PERSONA", "Individuo umano"),
    ("PIANETA", "Corpo celeste in orbita"),
    ("PIOGGIA", "Acqua che cade dal cielo"),
    ("POMODORO", "Frutto rosso per la salsa"),
    ("PRIMAVERA", "Stagione del risveglio"),
    ("PROFUMO", "Fragranza piacevole"),
    ("QUERCIA", "Albero robusto e longevo"),
    ("RAGIONE", "Facolta del pensiero logico"),
    ("REGISTA", "Chi dirige un film"),
    ("RICETTA", "Istruzioni per cucinare"),
    ("RISPOSTA", "Replica a una domanda"),
    ("RIVISTA", "Pubblicazione periodica"),
    ("SABBIA", "Granelli finissimi di roccia"),
    ("SALOTTO", "Stanza per ricevere gli ospiti"),
    ("SCATOLA", "Contenitore con coperchio"),
    ("SCIENZA", "Conoscenza sistematica della natura"),
    ("SCULTURA", "Opera d'arte tridimensionale"),
    ("SEMAFORO", "Segnale luminoso stradale"),
    ("SENTIERO", "Piccola via di campagna"),
    ("SERPENTE", "Rettile senza zampe"),
    ("SILENZIO", "Assenza totale di suoni"),
    ("SIMBOLO", "Segno che rappresenta altro"),
    ("SORGENTE", "Punto dove nasce un corso d'acqua"),
    ("SPECCHIO", "Superficie che riflette l'immagine"),
    ("SPIRALE", "Curva che gira su se stessa"),
    ("SQUADRA", "Gruppo organizzato di persone"),
    ("STAGIONE", "Una delle quattro parti dell'anno"),
    ("TARTARUGA", "Rettile con il guscio"),
    ("TELEFONO", "Apparecchio per comunicare a distanza"),
    ("TEMPESTA", "Forte perturbazione atmosferica"),
    ("TESORO", "Grande ricchezza nascosta"),
    ("TORNADO", "Violento turbine di vento"),
    ("TROMBA", "Strumento musicale a fiato"),
    ("TUMORE", "Crescita anomala di cellule"),
    ("UNIVERSO", "Totalita dello spazio e della materia"),
    ("VAMPIRO", "Creatura che beve il sangue"),
    ("VENTAGLIO", "Oggetto per farsi vento"),
    ("VERDURA", "Ortaggi commestibili"),
    ("VESUVIO", "Vulcano vicino a Napoli"),
    ("VITTORIA", "Successo in una competizione"),
    ("VULCANO", "Montagna che erutta lava"),
    ("ZAFFIRO", "Pietra preziosa azzurra"),
    ("ZANZARA", "Insetto che punge e succhia sangue"),
    ("ZUCCHERO", "Dolcificante cristallino bianco"),
]

# Definizioni organizzate per lunghezza (usato dal motore)
def get_words_by_length(min_len=3, max_len=15):
    """Restituisce le parole filtrate per lunghezza."""
    return [(w, d) for w, d in WORDS if min_len <= len(w) <= max_len]

def get_clue(word):
    """Restituisce la definizione di una parola."""
    for w, d in WORDS:
        if w == word:
            return d
    return "Definizione non disponibile"
